### ISSUE TITLE
command 'prettier.format' not found

### ISSUE THREAD

**Issue by suancarloj** [esbenp/prettier-vscode#1]
Hey, I just tried your plugin but unfortunately I cannot get it to work, I keep getting 

> command 'prettier.format' not found

Any idea why ?

Currently on osx, with vscode 1.8.1 

In vscode console I can see this: 

``` 
[Extension Host] Activating extension esbenp.prettier-vscode failed: {1}. extensionHost.ts:293
[Extension Host] Activating extension esbenp.prettier-vscode failed:  undefined extensionHost.ts:293
```

I tried with prettier installed globally and locally
Thanks :)

**Comment by samspade** [comment]
Same happens to me on Windows 10, VSCode,1.8.1

**Comment by colek42** [comment]
ubuntu 16.04, same issue.

**Comment by esbenp** [comment]
Hey, all. Terribly sorry, I should have tested this better.

The error has been fixed in 0.1.6

**Comment by thongdong7** [comment]
In my keybinding, I use

```json
  {
    "key": "ctrl+shift+f",
    "command": "prettier.format",
    "when": "editorHasDocumentFormattingProvider && editorTextFocus && !editorReadonly"
  }
```

which will cause the error.

Change to

```json
  {
    "key": "ctrl+shift+f",
    "command": "editor.action.formatDocument",
    "when": "editorHasDocumentFormattingProvider && editorTextFocus && !editorReadonly"
  }
```

fixed it. (version 0.7.1)

**Comment by esbenp** [comment]
@thongdong7 `0.7.0+` has removed the `prettier.format` action and works as a replace for VS Codes native javascript formattter https://github.com/esbenp/prettier-vscode/releases/tag/0.7.0
