### ISSUE TITLE
Prettier doesn't working!

### ISSUE THREAD

**Issue by svipben** [esbenp/prettier-vscode#101]
Hello,

semi is true in config by default, but when I use `CTRL + SHIFT + I` it doesn't add `;`. I'm using last version of prettier and last version of this plugin, VS Code is also last version as well as Node.js. Using `prettier` CLI everything fine, but using this plugin something is really bad, it sometimes even make this:

```
module.exports = 'hello'
  ;
```

It seems `prettier.semi` isn't working, because it doesn't matter if it's false or true. Also it doesn't matter if `prettier` package is installed or not.

I also get this in VS Code developer tools: ```Activating extension `esbenp.prettier-vscode` failed: Cannot find module 'read-pkg-up'```

**Comment by svipben** [comment]
Seems `prettier` isn't working at all... And I think everything is because of this: ```Activating extension `esbenp.prettier-vscode` failed: Cannot find module 'read-pkg-up'```

**Comment by CiGit** [comment]
Can you try to uninstall reinstall the extension ?
I've just downloaded the published vsix package and it contains this module.

**Comment by svipben** [comment]
@CiGit Thanks, I uninstalled and then installed the extension and now it works. I don't know why I didn't did that before opening the issue :smile:

**Comment by CiGit** [comment]
So it seems there is a problem with *something* but not this extension :-)
