### ISSUE TITLE
semicolons after insert

### ISSUE THREAD

**Issue by pvpshoot** [esbenp/prettier-vscode#104]
Hi how can i disable to insert semicolon and new line after insert (cmd+v); ?

**Comment by CiGit** [comment]
I've seen some troubles with the formater and formatOnPaste.
Disable formatOnPaste (at least for javascript)

Note: It comes from our `DocumentRangeFormattingEditProvider`

**Comment by pvpshoot** [comment]
U can go to extension folder and remove js from VALID_LANG constant 
it situated in ` ~/.vscode/extensions/esbenp.prettier-vscode-0.17.1/out/src/extension.js`

**Comment by CiGit** [comment]
@pvpshoot This will simply prevent prettier from running on JS files.

**Comment by pvpshoot** [comment]
oh, yep...
i will remove my post, sorry

**Comment by CiGit** [comment]
Our range formater gets improved. This should be fixed. Thanks to @josephfrazier
