### ISSUE TITLE
Shortcut for Windows users?

### ISSUE THREAD

**Issue by nicnash** [esbenp/prettier-vscode#105]
CMD + shift + P does not exist for windows 10 users.  Currently the only way I know of to run a new command is to do format on save (which may not be desired)

WIN + shift + P switches display modes
No other combinations work

Do y'all know of another work around?  maybe make a hotkey to run it?

**Comment by CiGit** [comment]
Seems you are searching for the command palette. `CTRL + SHIFT + P` on windows/linux

**Comment by GollyJer** [comment]
`CTRL + ALT + F` works for me on Windows 10.

**Comment by richardtallent** [comment]
Could we add this to the docs? The same question came up when I was extolling the virtues of Prettier on a call with Windows VS devs, and I'd only used it so far in VS Code on a Mac.

**Comment by CiGit** [comment]
Command palette is on VSCode's start screen:
![image](https://cloud.githubusercontent.com/assets/1453420/26733642/be8c27d8-47bb-11e7-948b-6f7d0442f9d9.png)
From there you can find any shortcut.

We could add `Format Document` **default** shortcut for various OS to the doc. I'm not sure if those shortcuts are also Keyboard dependent (for reference this screenshot is for Windows, fr_CH `QWERTZ` kb)

**Comment by GollyJer** [comment]
The best way is to go to `File > Preferences > Keyboard Shortcuts` and search for the work `format`.

**Comment by CiGit** [comment]
Feel free to reopen if there is something new

**Comment by fisehara** [comment]
@GollyJer Thanks for Shift+Alt+F which also works on OSX

**Comment by Gregam3** [comment]
For whatever reason on my ubuntu system I have to use `Ctrl + Shift + I`
