### ISSUE TITLE
every folder have prettier config

### ISSUE THREAD

**Issue by monkindey** [esbenp/prettier-vscode#106]
I contributed a project with it's eslint config which will break my prettier config.
The prettier config now is global. How about to support every folder have itself prettier config and I can configure the prettier config for the project.

**Comment by CiGit** [comment]
You can use prettier-eslint through `eslintIntegration`.

You may also configure vscode per workspace. `Workspace settings`

**Comment by monkindey** [comment]
Appreciate for your direction. I try it.
