### ISSUE TITLE
"prettier.eslintIntegration": true not working on Windows 10

### ISSUE THREAD

**Issue by GollyJer** [esbenp/prettier-vscode#107]
I've run into this problem with the prettier-eslint-vscode extension and tried yours without any luck as well.

I'm running this version of vscode.
![screenshot_07](https://cloud.githubusercontent.com/assets/689204/26587111/64e6a756-451f-11e7-96a3-4bf680d1e6d0.png)
and `prettier` gets applied but `eslint --fix` does not.

**Comment by CiGit** [comment]
I've just tried a freshly installed insider on Windows 10 and `eslintIntegration` without any trouble.
Can you share a minimal input code and your settings which exposes the problem you have?

**Comment by GollyJer** [comment]
Hi @CiGit. Thanks for the response!

With that info I was able to track the problem down to, strangely, the [Git Lens](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens) extension. 

Can you install it and see if it breaks for you?

**Comment by CiGit** [comment]
Tested on Archlinux, stable vscode, a lot of extensions (including git lens) without having errors. Will try on Windows 10 later.
Is this issue relevant to #96 ?

**Comment by GollyJer** [comment]
I don't think #96 is related to my issue.

Just to isolate further I disabled every extension except for yours and GitLens and added only `"prettier.eslintIntegration": true` to my settings.json file.  

The problem is 100% reproduce-able.  
With GitLens, no `eslint --fix`. Without GitLens it works as expected. 

The same thing happens with @RobinMalfait's extension.

**Comment by CiGit** [comment]
That's really weird... 
Windows 10 + vscode stable + git lens without troubles.

**Comment by CiGit** [comment]
Please update to latest version, It updates prettier-eslint...
It's worth a try 😆

**Comment by GollyJer** [comment]
Definitely weird!
New version doesn't fix anything. :-/

The only thing I can think of is that I'm on vscode-insiders.
I'll do without GitLens for now. 😄 

Thanks for trying.

**Comment by CiGit** [comment]
Tried with Insider + Git Lens + eslintIntegration.
I've got the same behavior you described. It seems it also breaks eslint extension.

### Quick and Dirty fix
By patching `~\.vscode-insiders\extensions\eamodio.gitlens-3.5.1\node_modules\zone.js\dist\zone-node.js:816`

```js
 if (ZoneAwareError[stackRewrite] && error.originalStack) {
```
to 
```js
if (ZoneAwareError[stackRewrite] && typeof error.originalStack === 'string') {
```
Prettier-vscode runs smoothly. Git lens seems to work too.

**Comment by GollyJer** [comment]
A [fix from the GitLens side is in the works](https://github.com/eamodio/vscode-gitlens/issues/79#issuecomment-305853348
).

**Comment by CiGit** [comment]
Thanks.
There is nothing we can do on our side. Closing
