### ISSUE TITLE
Breaks indentation when formatting only selection 

### ISSUE THREAD

**Issue by gs-akhan** [esbenp/prettier-vscode#109]
Hi,
Is it intentional when we format selected in VSCode. It makes code start from left:0 and doesn't preserve existing Indentations .

Before Formatting : 
![screen shot 2017-06-02 at 1 33 10 am](https://cloud.githubusercontent.com/assets/5646166/26698414/83b98886-4733-11e7-871e-bd7c8090cd5f.png)

After Formatting only selection : 
![screen shot 2017-06-02 at 1 33 20 am](https://cloud.githubusercontent.com/assets/5646166/26698423/8dac419e-4733-11e7-844e-94ef10a8cd74.png)

Thanks

**Comment by CiGit** [comment]
Our range formater is far from perfect and I'm considering disabling it until we can figure out a good way to do it.
Prettier will provide a range formater soon.
