### ISSUE TITLE
CSS support?

### ISSUE THREAD

**Issue by nicolazj** [esbenp/prettier-vscode#110]
Will you consider to support CSS formatting?
since prettier can format .css files

**Comment by CiGit** [comment]
Definitely. Once it lands in prettier.

**Comment by screendriver** [comment]
[Prettier 1.0.4](https://github.com/prettier/prettier/releases/tag/1.4.0) is out now with CSS support ;-)

**Comment by anthony2025** [comment]
I wonder, would just changing VALID_LANG in extension.ts, and activationEvents in package.json be enough to activate the new languages or would other changes be needed? if so I could make a quick PR

**Comment by CiGit** [comment]
Fixed in Version 0.18.0
