### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by screendriver** [esbenp/prettier-vscode#111]
Since [Prettier 1.4.0](https://github.com/prettier/prettier/releases/tag/1.4.0) was released today with TypeScript support it would be awesome if `prettier-vscode` would support that too :relaxed:

**Comment by CiGit** [comment]
Fixed in Version 0.18.0

**Comment by steadicat** [comment]
Did you forget to add `typescript` to the list of parser options? https://github.com/esbenp/prettier-vscode/blob/99bde3c862efe93c82bc7a5ac6c468fdd10c92ae/package.json#L92

**Comment by CiGit** [comment]
No, this was on purpose.
The typescript parser will be selected on typescript files. Flow/babylon depending on your settings for JS.
