### ISSUE TITLE
Prettier exclude css

### ISSUE THREAD

**Issue by dacz** [esbenp/prettier-vscode#115]
Please, add possibility to exclude css from prettier or support postcss/nextcss (as #114). Currently using stylefmt and happy with it, same as I'm happy with prettier for javascript.

Thanks a lot for your plugin, it helps a lot!

**Comment by CiGit** [comment]
I'm thinking of it. I'd like settings to be easy.
I may have something:
Allow to edit something like
```json
{
    js: ['javascript', 'javascriptreact', 'jsx'],
    ts: ['typescript', 'typescriptreact'],
    css: ['css', 'less', 'sass'],
}
}
```

**Comment by CiGit** [comment]
I could not decide on adding or removing. Does #116 fits your needs?

**Comment by dacz** [comment]
Thanks! It fits my needs.
