### ISSUE TITLE
Unable to install extension version 0.19.0

### ISSUE THREAD

**Issue by vsaarinen** [esbenp/prettier-vscode#118]
Upgrading to the latest version of the extension seems to have uninstalled the extension, and trying to re-install the extension from the marketplace does nothing – the "Install" button changes to "Installing" for a few seconds, and then gets reverted back to "Install". Restarting VSCode does not fix the problem.

If there's some way to enable debug logging for extension installation, I can add the logs here.

**Comment by CiGit** [comment]
Maybe toggle developer tool.
It may be worth looking into ´.vscode/extensions/´

**Comment by vsaarinen** [comment]
The developer tools' console had an error which said: "An unknown error occurred. Please see the log."

The `~/.vscode/extenstions` folder had an `esbenp.prettier-vscode-0.19.0` folder in it that only contained `node_modules`. I removed the `esbenp.prettier-vscode-0.19.0` folder, tried reinstalling the extension, and now it went through ok. The problem is now resolved for me – let's hope that it's a freak occurrence that doesn't happen to others.

**Comment by CiGit** [comment]
Great you fixed it. It would be great if you could find the logs tho

**Comment by vsaarinen** [comment]
Do you have any idea where the logs are located? I can't find anything under `~/.vscode`.

**Comment by CiGit** [comment]
Sadly .... I've no idea...

**Comment by joewood** [comment]
Having the same issue, haven't resolve it yet. I've tried installing from the command-line and I'm seeing several "self signed cert" errors (I'm running through a proxy). Strict SSL is off, so it should work fine (other extensions are fine).

**Comment by joewood** [comment]
Not sure if this helps, but the install fails on vscode with this:
```
[ { Error: ENOENT: no such file or directory, open 'f:\vscode\extensions\esbenp.prettier-vscode-0.19.0\package.json'
    errno: -4058,
    code: 'ENOENT',
    syscall: 'open',
    path: 'f:\\vscode\\extensions\\esbenp.prettier-vscode-0.19.0\\package.json' } ]
```

I use an alternative extensions dir (specified in the command line).

**Comment by joewood** [comment]
I ended up resolving this by using a non-network drive as the alternative extensions dir. Not sure why this extension is sensitive to that.

**Comment by CiGit** [comment]
I've a strange feeling. I think it's one of the rare release I've built on Windows ...

**Comment by dburles** [comment]
Same issue just happened here too on mac

**Comment by CiGit** [comment]
New release 0.19.1 built the same way as 0.19.0.
Let's see if this happens again 😕

**Comment by CiGit** [comment]
Seems fixed.

**Comment by Vishwaas** [comment]
@vsaarinen  thanks that worked
