### ISSUE TITLE
prettier-miscellanous option/version?

### ISSUE THREAD

**Issue by langdonx** [esbenp/prettier-vscode#119]
Would it be difficult to include [prettier-miscellaneous](https://github.com/arijs/prettier-miscellaneous) as an option for this Extension?

Or would a fork of `prettier-vscode` be required?

**Comment by CiGit** [comment]
This will add some options which are useless to Prettier.  So I'm against this. 
I've seen two forks with prettier-miscellaneous. 
https://marketplace.visualstudio.com/items?itemName=passionkind.prettier-vscode-with-tabs
https://marketplace.visualstudio.com/items?itemName=remimarsal.prettier-now
