### ISSUE TITLE
Prettify as you type

### ISSUE THREAD

**Issue by colek42** [esbenp/prettier-vscode#12]
In the blog entry, it shows how live code reformating could happen.  I don't know if I would like this option, it might be distracting or counter-productive.  OTOH it could be awesome.  Thoughts?

**Comment by colek42** [comment]
ref: registerOnTypeFormattingEditProvider(selector: DocumentSelector, provider: OnTypeFormattingEditProvider, firstTriggerCharacter: string, ...moreTriggerCharacter: string[]): Disposable

**Comment by CiGit** [comment]
I've tested it slightly some time ago, with a quick implementation like you mentioned. It was not convincing for me. The problem would be to restore the cursor at the right place after prettier changed line position, insert/remove parentheses and certainly some more changes.

I've a ugly hacky idea in mind which *could* do the trick in most case i think. Will maybe come up with it once I find enough time to implement it.

Feel free to share any idea to resolve the cursor tracking-restore trouble.

**Comment by CiGit** [comment]
This is not something which seems to be asked a lot. I think it's not worth the trouble (sorry @colek42 )
Will reopen on next riot 😆

**Comment by josephfrazier** [comment]
FYI Prettier v1.4.0 comes with basic support for cursor tracking: https://github.com/prettier/prettier/pull/1637

**Comment by CiGit** [comment]
Yes, this should resolve a lot of troubles ;-)
But I think we will need prettier/prettier#1869 (*soon*?)
There is no emergency on that one tho.
