### ISSUE TITLE
Can the config be shared with command line use of prettier.

### ISSUE THREAD

**Issue by SteveALee** [esbenp/prettier-vscode#124]
For example it makes sense to have prettier set to run on save but the exact same settings will be needed for a git hook or CI processing

As far as I can see as Prettier doesn't use package.json for settings but the command line this won't be possible without an upstream patch.

**Comment by CiGit** [comment]
Right, this should be in prettier IMHO. This way, every Editor extension would work the same.

**Comment by bradleyayers** [comment]
This is supported now https://github.com/prettier/prettier/blame/master/README.md#L627

**Comment by CiGit** [comment]
@bradleyayers Not yet released :-) I've currently a test version https://github.com/CiGit/prettier-vscode/releases/tag/v0.22.0-alpha

**Comment by bajtos** [comment]
@CiGit hello, what's the status of this feature? I see that 0.22.0 has been released, but it does not seem to apply settings from `.prettierrc` yet (tested using 0.22.1).

**Comment by RobinMalfait** [comment]
@bajtos it is still not released on the prettier repo itself. Last release was 27 jun (https://github.com/prettier/prettier/releases)

**Comment by bajtos** [comment]
Thanks, I did not realize the feature was not released in prettier yet. For anybody coming to this issue in the future, here are few links where to find more information (and perhaps the latest status):

 - The issue tracking `prettier@1.6.0` release: https://github.com/prettier/prettier/issues/2589
 - The pull request which added support for config files, there is release-date-releated discussion at the bottom: https://github.com/prettier/prettier/pull/2434

**Comment by bajtos** [comment]
@CiGit @RobinMalfait as you probably now, Prettier 1.6.0 was released yesterday. Any ETA for the new version of prettier-vscode that will support `.prettierrc`? How can I help to make that happen?

**Comment by CiGit** [comment]
ETA: 12 minutes ago

**Comment by SteveALee** [comment]
I never said - thanks!
