### ISSUE TITLE
Specify path to prettier

### ISSUE THREAD

**Issue by ccorcos** [esbenp/prettier-vscode#125]
In VSCode, I'm using this option to specify a local installation of typescript so that everyone in our team can work off the same version. It would be nice if we could do this for prettier as well

	"typescript.tsdk": "./node_modules/typescript/lib",

**Comment by utkuturunc** [comment]
It would be even nicer if we could point it to prettier-miscellaneous

**Comment by CiGit** [comment]
This extension already makes use of `./node_modules/prettier` if it is in package.json's dependecies or devDependecies.

**Comment by ccorcos** [comment]
oh sweet :)
