### ISSUE TITLE
emoji in a comment causes next multiline comment to have newlines removed

### ISSUE THREAD

**Issue by Haroenv** [esbenp/prettier-vscode#126]
see https://github.com/prettier/prettier/issues/2091#issuecomment-307572969

When using prettier on the web or command line, this doesn’t happen

**Comment by CiGit** [comment]
@Haroenv Is this still happening ?
I'm trying to reproduce it:
```js
// capital 😡

/**
 * Set the html stub
 */
const stub = fs
  .readFileSync('./__tests__/stub.html')
  .toString();

function setStub() {

}
/**
 */
```
turns into:
```js
// capital 😡

/**
 * Set the html stub
 */
const stub = fs.readFileSync('./__tests__/stub.html').toString();

function setStub() {}
/**
 */

```
If yes, I would need your config / Line endings / OS / VSCode version.

**Comment by Haroenv** [comment]
Yes, as said in the other issue, this actually might be a bug in the flow version of prettier, since I can reproduce the difference with and without emoji on the site as well

[link](https://prettier.github.io/prettier/#%7B%22content%22%3A%22%2F%2F%20capital%20😡%5Cn%5Cn%2F**%5Cn%20*%20Set%20the%20html%20stub%5Cn%20*%2F%5Cnconst%20stub%20%3D%20fs%5Cn%20%20.readFileSync('.%2F__tests__%2Fstub.html')%5Cn%20%20.toString()%3B%5Cn%5Cnfunction%20setStub()%20%7B%5Cn%5Cn%7D%5Cn%2F**%5Cn%20*%2F%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22flow%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D)

**Comment by CiGit** [comment]
Great you found it out!
