### ISSUE TITLE
Doesn't support CSS

### ISSUE THREAD

**Issue by ronihcohen** [esbenp/prettier-vscode#127]
```
prettier --version
1.4.4
```
but still getting this error:

![image](https://user-images.githubusercontent.com/3350618/27010345-058ff9f2-4eab-11e7-9690-1f89d736e3d4.png)

**Comment by CiGit** [comment]
Have you prettier 1.3.1 in your package.json?

**Comment by ronihcohen** [comment]
Yes, but happens also after updating `package.json` to ` "prettier": "^1.4.4"`

**Comment by CiGit** [comment]
Just to be sure, I was also meaning installing prettier 1.4.4 :-)

Can you provide your file structure? 
At least the file you are trying to format and every `package.json` which contains *prettier* upwards

**Comment by CiGit** [comment]
Stalled, closing.
