### ISSUE TITLE
Errors not going away

### ISSUE THREAD

**Issue by jackfranklin** [esbenp/prettier-vscode#128]
If I make a syntax error, Prettier shows me the error bar at the top that says "Unexpected error, expected `,`", or something along those lines.

That's fine, but I find it a bit frustrating that these errors don't go away after a set time period, or if when I then save again and fix my error, the message doesn't go away. In addition, any new messages seem to stack, whereas potentially it would be better to simply have the newest message replace any others. I'm proposing some changes such that:

1. Only one error message ever shown at once
2. The error messages time out after X seconds (could be turned on/off in config)
3. On a successful format, any Prettier errors are removed.

I am happy to take a stab at a PR if you think anything along these lines would be useful :) Thanks for all your hard work with the extension 🎉

**Comment by CiGit** [comment]
We are not doing a good job with errors ( #55 ) 
You can press `ESC` key to remove those errors currently.
I would love
> On a successful format, any Prettier errors are removed.

with a little change:
On a successful format, any prettier errors **for the formatted files** goes away.

We are able to format multiple files and thus having errors for all of those.
Scenario: formatOnSave, saveAll, multiple errors.

**Comment by jackfranklin** [comment]
For some reason the `ESC` key doesn't clear them for me - I suspect this is because I have VSCode-Vim which is overriding the ESC key. I'm not sure of a good way to get round that.

Other than that I agree with your plan that it sounds good. I'd also like an option to silence all errors (usually ESLint picks them up and underlines them in my editor so I don't need Prettier to tell me about them).

**Comment by CiGit** [comment]
I think it's not prettier's role to point those mistakes but any linter.
I see an alternative to that. Having every errors in an `outputChanel` (see #55). If parsing errors can be clickable this would be great.

Do you want to PR this?

**Comment by jackfranklin** [comment]
I think an option to disable Prettier giving error messages that's `false` by default would be reasonable - but happy to  be disagreed with! :)

I don't really understand what the `outputChannel` is - what would that look like in the editor? (I'm still new to VSCode!)

**Comment by CiGit** [comment]
I'd like to avoid options :-) 
The outputChanel is a write only panel at the bottom of  VSCode.
![image](https://user-images.githubusercontent.com/1453420/27439716-e3a4d850-5768-11e7-85ac-dbf2203f4c60.png)

**Comment by jackfranklin** [comment]
Ah understood - I would agree that would be the best place to have the output. If you have them there would you then get rid of the error at the top of the page?

**Comment by CiGit** [comment]
Yes, it was *instead of* except for some errors we want to be sure to notify the user

**Comment by RobinMalfait** [comment]
@CiGit I was the maintainer of https://github.com/RobinMalfait/prettier-eslint-code and deprecated it in favour of this package. In that package we had a statusbar message indicating problems or not using a check mark or a cross.

When clicking on it, we showed the actual error using an outputChannel.

Would you like a PR where I implement it for this package and also add an option to hide/show that statusbar message?

I think that the error handling right now is annoying due to the popups.

**Comment by CiGit** [comment]
@RobinMalfait Yes for a PR!

- I don't get the point of the option. Isn't it something minimal?
- Is it possible to have clickable links in the output for errors which have a `file:loc` info?

It annoys myself 😕

**Comment by RobinMalfait** [comment]
@CiGit I opened a PR, and the statusbar item is indeed minimal, but I had people request options to hide it. Feel free to have a chat on the PR #152

**Comment by CiGit** [comment]
Changed in 0.21.0 and certainly fixed :-)
