### ISSUE TITLE
How to use in windows vscode?

### ISSUE THREAD

**Issue by sihitejulio** [esbenp/prettier-vscode#131]
How to use in windows vscode?

**Comment by CiGit** [comment]
CTRL + SHIFT + P -> format document

**Comment by akolssontd** [comment]
On a Windows PC, when I do "CTRL + SHIFT + P", it opens the command palette. I haven't figured out how to trigger format. I'm using VSC 1.13.1

**Comment by CiGit** [comment]
I think you get your answer. Please reopen if that's not the case.

**Comment by raybooysen** [comment]
Probably worth re-opening if only to update the README.md.  The instructions sal CTRL + SHIFT + P

**Comment by RobinMalfait** [comment]
The documentation specifically states `Using Command Palette` so that is the <kbd>CTRL/CMD</kbd>+<kbd>SHIFT</kbd>+<kbd>P</kbd> key combination.

We always welcome fresh PR's with clarifications to update the readme 😄

**Comment by raybooysen** [comment]
Maybe I missed something but CTRL-SHIFT-P doesn't work on windows in vscode, it's CTRL-SHIFT-F

**Comment by RobinMalfait** [comment]
Doesn't <kbd>CTRL/CMD</kbd>+<kbd>SHIFT</kbd>+<kbd>P</kbd> trigger the Command Palette?

**Comment by raybooysen** [comment]
Got it!  I misread
