### ISSUE TITLE
Suggestion: only ever use locally installed Prettier version

### ISSUE THREAD

**Issue by will-stone** [esbenp/prettier-vscode#132]
Some of my colleagues are yet to embrace Prettier, and so when working on their projects, I have to disable this extension. May I suggest that this only runs if Prettier is present on the project? This would also mean the user is in complete control of the version of Prettier that is used, without accidentally using your bundled version.

Either that or a nice way to disable Prettier (like Atom's status bar button).

**Comment by CiGit** [comment]
In my case, I use it, my colleagues don't (yet). I like not having to install prettier in every project.
I may also have some project which are not npm projects or simply some single files around I also would like to be formatted. 

VSCode is able to disable a given extension in a workspace. You have to do it once per workspace.
With our architecture and some status bar button it would disable every formater for each language we cover and it doesn't convince me you would avoid an accidental format as you still have to think to click on it first.

**Comment by will-stone** [comment]
Installing Prettier into a project wouldn't affect your colleagues that don't have this extension. As for running this on the odd file with no package.json, I suppose you have a point there. I think where I feel uncomfortable is having to check every project's package.json to see if prettier is installed. Well, the way it usually ends-up happening:

1. save file
2. whole file reformats, damn!
3. undo changes
4. disable prettier for workspace
5. redo changes
6. resave file

**Comment by CiGit** [comment]
My first part was to point out that I can use prettier on project where people use different formater. And I was just curious why you couldn't :-)

Having certainly other constrains than I have, I get your trouble.
Undo doesn't undo only the format part?

**Comment by will-stone** [comment]
I like to use format on save in my workflow. Therefore, if a project doesn't use Prettier and I don't want git to look like I've changed nearly every line of code, I must disable either format on save or prettier. Maybe that's my issue, I just need something to easily toggle format-on-save. I think it was StandardJS that only activated if it was present in the project, I think that was where I was getting the idea for this issue from.

**Comment by CiGit** [comment]
Disabling one or the other will have a different behavior.
By disabling prettier you still will have the default formater kicking in.

It seems you have half a solution. I don't see the other half :confused:

**Comment by will-stone** [comment]
Yeah, let's close this off. People are obviously now used to the workflow of this plug-in and any change like the one I was proposing would probably cause confusion. Maybe I'll make a toggle-formatter extension. Thanks.
