### ISSUE TITLE
Cannot read property 'node' of undefined

### ISSUE THREAD

**Issue by OliverJAsh** [esbenp/prettier-vscode#133]
Quite frequently I get this error:

```
Cannot read property 'node' of undefined
```

![image](https://user-images.githubusercontent.com/921609/27445156-c765fc54-5746-11e7-974e-4102d6bafcd9.png)

I tried to narrow down the issue. With all extensions except prettier disabled, using the default prettier settings, here is the smallest use case I could find:

``` js
// comment
import React from 'react';
```

Select line 2 and run the "Format Selection" command, and you will get the error.

**Comment by CiGit** [comment]
I had that one sometimes today without even formatting. I was working on typescript files.
The stack trace I had was not clear to me. Will try to investigate a little more.
Can you share your stack trace if you have one ? `Help -> Toggle developer tool` under console.

**Comment by OliverJAsh** [comment]
```
Cannot read property 'node' of undefined
e.doShow @ messageService.ts:125
e.show @ messageService.ts:104
t.showMessage @ mainThreadMessageService.ts:64
n.Class.derive._oncancel @ winjs.base.raw.js:1641
t.showMessage @ mainThreadMessageService.ts:34
t.$showMessage @ mainThreadMessageService.ts:28
e.handle @ abstractThreadService.ts:34
s @ ipcRemoteCom.ts:275
f @ ipcRemoteCom.ts:231
_combinedTickCallback @ internal/process/next_tick.js:67
_tickCallback @ internal/process/next_tick.js:98
```

**Comment by OliverJAsh** [comment]
Oddly, this doesn't occur when I use `prettier.eslintIntegration`

**Comment by CiGit** [comment]
Found out. This is the Range formater (which is disabled with eslint, fallback to entire file.)
`echo "import x from 'x'" | prettier --range-start 1 --range-end 2` Inside `importDeclaration`
```
stdin: TypeError: Cannot read property 'node' of undefined
    at findSiblingAncestors (/usr/lib/node_modules/prettier/index.js:12811:44)
    at calculateRange (/usr/lib/node_modules/prettier/index.js:12922:28)
    at formatRange (/usr/lib/node_modules/prettier/index.js:12939:19)
    at formatWithCursor (/usr/lib/node_modules/prettier/index.js:12769:30)
    at Object.formatWithCursor (/usr/lib/node_modules/prettier/index.js:12975:12)
    at format (/usr/lib/node_modules/prettier/bin/prettier.js:5475:19)
    at getStdin.then.input (/usr/lib/node_modules/prettier/bin/prettier.js:5542:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
```
Found also out if you select nothing but whitespace it throws the same, as long as it's in the top level (outside of `Program`'s body):
`echo "  let a;" | prettier --range-start 1 --range-end 2`
`echo "let a;   " | prettier --range-start 7 --range-end 8`
`echo "let a;   let b" | prettier --range-start 7 --range-end 8`

cc @josephfrazier

**Comment by CiGit** [comment]
Fixed with latest release.
