### ISSUE TITLE
Ability to override inferred settings from ESLint

### ISSUE THREAD

**Issue by OliverJAsh** [esbenp/prettier-vscode#135]
Sometimes it is necessary to override the settings inferred from ESLint. This is possible with the prettier-eslint CLI by specifying extra command line arguments. However, this extension uses the specified settings as fallbacks instead, and there is no way to override the inferred settings.

**Comment by OliverJAsh** [comment]
This could be done using the `prettierOptions` option instead/as well as the `fallbackPrettierOptions` option: https://github.com/prettier/prettier-eslint#prettieroptions-object

**Comment by CiGit** [comment]
Yes we choose the fallback option as it was making more sens. At least to me. Having your linter be your source of truth. 
Do you have a use case?

**Comment by CiGit** [comment]
Stalled, closing.
