### ISSUE TITLE
printWidth setting is ignored when max-len ESLint rule is explicitly disabled

### ISSUE THREAD

**Issue by OliverJAsh** [esbenp/prettier-vscode#136]
Given ESLint rule `max-len: 0` (explicitly disabled) and a `prettier.printWidth` setting (e.g. 80), this extension ignores the `prettier.printWidth` setting and instead uses the fallback (80).

**Comment by OliverJAsh** [comment]
Potentially related https://github.com/prettier/prettier-eslint/issues/97

**Comment by CiGit** [comment]
Seems highly related to me

**Comment by CiGit** [comment]
just published an updated version with your fix ;-)
