### ISSUE TITLE
Add support for prettier-eslint

### ISSUE THREAD

**Issue by esbenp** [esbenp/prettier-vscode#14]
https://github.com/kentcdodds/prettier-eslint

**Comment by colek42** [comment]
This will let me get rid of my git hooks!

**Comment by replete** [comment]
This would be fantastic!

**Comment by CiGit** [comment]
There are more project which you may consider
 [projects](https://github.com/jlongster/prettier#related-projects)

**Comment by CiGit** [comment]
Some thoughts about prettier-eslint:
I would expect people using eslint to also have the Eslint extension. So I think it would be possible to call `eslint.executeAutoFix` after having run prettier. (Cross-extension call)

**Comment by CiGit** [comment]
It's done by https://marketplace.visualstudio.com/items?itemName=RobinMalfait.prettier-eslint-vscode
Closing

**Comment by batjko** [comment]
Has this been removed from the vscode extension store?
Suddenly disabled in my editor and I can't find it in the list anymore:
![image](https://user-images.githubusercontent.com/7287076/28017858-e0bc1406-6572-11e7-8071-e4139dd41105.png)

**Comment by RobinMalfait** [comment]
@batjko I removed the `prettier-eslint` extension from the store.

Good news: You can enable `prettier.eslintIntegration` using [this plugin](https://github.com/esbenp/prettier-vscode)! So there was no need to keep supporting that other extension.

**Comment by batjko** [comment]
@RobinMalfait Well that's good to know. I'm a little taken aback that an extension can just be uninstalled from my local editor without my knowledge. Some deprecation announcement would have been nice as well.

**Comment by RobinMalfait** [comment]
@batjko There was a deprecation notice, after that I removed it.

**Comment by bySabi** [comment]
I add two extension to market-place. It just `prettier-vscode` patched for  use **semistandard** or **standard** in place of *eslint*

* https://marketplace.visualstudio.com/items?itemName=bysabi.prettier-vscode-semistandard
* https://marketplace.visualstudio.com/items?itemName=bysabi.prettier-vscode-standard

This is the patcher: https://github.com/bySabi/patch--prettier-vscode

**Comment by batjko** [comment]
@RobinMalfait Sorry I didn't see anything in the editor. Was it just on Github or something?
I don't think people can be reasonably expected to regularly revisit all their extension's homepages just to check if they may get removed soon.

Anyway, it's not a big deal, but clearly communication for such cases could be better - perhaps a notification inside the editor?

**Comment by RobinMalfait** [comment]
@batjko I will do that the next time, if I have no other things to do ;)

**Comment by CiGit** [comment]
That make me think, we should update `JavaScript formatter` ...
@batjko I'm surprised vscode silently uninstalled a deprecated extension, instead of just preventing it's installation.

**Comment by batjko** [comment]
> @batjko I'm surprised vscode silently uninstalled a deprecated extension, instead of just preventing it's installation.

So was I. I was wondering why my code suddenly doesn't get re-formatted anymore. I check my extensions and it was simply gone. It's not a necessarily an issue with this extension, but with how VSC handles the deprecation of extensions, if this is possible.
