### ISSUE TITLE
[typescript] Format Document is ignoring editor.tabSize (and .eslintrc and tslint.json)

### ISSUE THREAD

**Issue by rossipedia** [esbenp/prettier-vscode#140]
It seems as though the typescript formatting is ignoring `editor.tabSize` and always formatting with a tab size of `2`.

I made a recording to demonstrate the issue (in this recording I have every plugin except for prettier disabled):

http://imgur.com/a/MBs5b

If I disable `prettier-vscode`, then the file gets formatted correctly with an indent of `4`.

**Comment by CiGit** [comment]
The setting is **prettier.tabWidth (default: 2)**
We are inferring from eslintrc only with eslintIntegration and on JS files.

**Comment by rossipedia** [comment]
any particular reason not to infer from either `.editorconfig` or `tslint.json`?

**Comment by CiGit** [comment]
For tslint, see prettier/prettier-eslint#92

For editorconfig, see #81 

I may want at some point to support editor.tabSize & editor.insertSpace
This was not done before as prettier wasn't supporting tabs. And now we have those settings.

**Comment by flagello** [comment]
Considering that prettier now supports more than just JS, it'd be wise to support `editor.tabSize` as VSCode supports language-based `editor.tabSize`, as in:
```json
    "[js]": {
        "editor.tabSize": 2
    },
    "[json]": {
        "editor.tabSize": 4
    }
```

**Comment by CiGit** [comment]
@flagello that's a great solution. 
There still is the trouble with printWidth / trailingComma we also want to support. see #130

**Comment by CiGit** [comment]
Closing as the initial post has been replied
