### ISSUE TITLE
Trailing Comma "all" setting breaking JSON

### ISSUE THREAD

**Issue by kkemple** [esbenp/prettier-vscode#141]
Having the trailing comma option set to `all` sets it on JSON entries as well. This is causing syntax errors and I have to disable prettier to edit JSON files unless I turn of trailing commas.

![jun-27-2017 22-00-11](https://user-images.githubusercontent.com/3629876/27617419-2d988f5a-5b84-11e7-85a5-1d31ba0ba23a.gif)

**Comment by Goblinlordx** [comment]
I have a very similar issue... but it is doing it if I have any trailing comma setting.  It also seems to be saving my settings file even if I don't have it open and am doing something completely different.  It constantly resaves and reformats my settings.json file (with trailing commas).

**Comment by kpman** [comment]
@kkemple @Goblinlordx I have the same issue here.
Maybe this is a VSCode issue? https://github.com/Microsoft/vscode/issues/29701

**Comment by Goblinlordx** [comment]
I m pretty sure it started occurring when I updated prettier though and not a VScode update.  I really wish there was an easy way to revert to an older plugin version to test =/.

**Comment by CiGit** [comment]
For `trailing-comma all`, could you reopen prettier/prettier#2308 @kkemple 

For the other part of the issue, I don't get it for now.

**Comment by dacz** [comment]
I see they pushed patch for this 22 hours ago. Is it possible to update plugin, please? Thanks a lot.

**Comment by rafaelkallis** [comment]
quick fix: add `"prettier.jsonEnable": []` to your vscode settings

**Comment by dacz** [comment]
@infernojs thanks

**Comment by CiGit** [comment]
@dacz The patch is on master but not yet released. Diff between master and 1.5.2 (we bundle 1.5.1 for now) https://github.com/prettier/prettier/compare/1.5.2...master

@vjeux Do you plan on a patch release *soon*?

**Comment by cuth** [comment]
@rafaelkallis, do you get this error even after turning JSON off?

```
Unexpected token, expected ; (2:9)
```

**Comment by rafaelkallis** [comment]
@cuth having it only when editing json files. json still get saved though.

**Comment by CiGit** [comment]
@cuth your error seems weird to me. This doesn't seem to be a JSON error.

**Comment by cuth** [comment]
@CiGit, looks like it is just related to updating settings and upgrading prettier in node_modules but not restarting vscode. Thanks!!
