### ISSUE TITLE
Add option to disable prettier

### ISSUE THREAD

**Issue by wmaurer** [esbenp/prettier-vscode#146]
Our team VSCode and we have our workspace `.vscode\settings.json` checked in to source control so that is shared amongst the team.

We don't yet use prettier on all projects, so would like to disable it on a per-project basis, team-wide. If we had an option to be able to disable prettier, we could add it to the shared workspace settings.

I understand that it is possible to disable the the extension from the settings cog, (as mentioned in #40), but I have no idea where this is saved, certainly not in the workspace `settings.json`.

**Comment by CiGit** [comment]
I don't know where those disabled extensions are saved.
This is certainly an issue for VSCode. It seems to me I've seen something similar there.
Maybe some workaround for now:
- Use prettier everywhere :fire: 
- Disable formatOnSave in those workspace settings.

**Comment by CiGit** [comment]
And just thinking about it:
If you empty `javascriptEnable` array it will be disabled 🤣 (for javascript)
Same thing for the other `typescriptEnable` / `cssEnable`

**Comment by wmaurer** [comment]
Thanks for your response.

We're progressing towards everywhere ;-) On those projects where we're not using Prettier, we're still using formatOnSave, so disabling that is not really an option.

Your second suggestion of assigning empty arrays will probably work, thanks (a single disable option would be easier though!).

**Comment by CiGit** [comment]
> a single disable option would be easier though!

Maybe for your use case, but having multiple options to do the same would certainly lead to some confusion.

**Comment by alukach** [comment]
For any future reader, at current time of writing the following set to the Workspace settings.json did the trick for me (in my case, enabling `eslint` rather than `prettier` for a single project):

```json
{
  "eslint.format.enable": true,
  "[javascript]": {
    "editor.defaultFormatter": "dbaeumer.vscode-eslint"
  }
}
```

**Comment by stevage** [comment]
Thanks @alukach, that worked for me. I also had to add it for `"[vue]"` in my case. I really wish there was a more direct way of disabling prettier for a specific project or directory.
