### ISSUE TITLE
Prettier isn't formatting typescript correctly

### ISSUE THREAD

**Issue by dfischer** [esbenp/prettier-vscode#147]
Notice the diamond is formatted oddly:

<img width="606" alt="screen shot 2017-07-04 at 3 43 40 am" src="https://user-images.githubusercontent.com/2424/27827203-fd782cae-606a-11e7-8106-41a9e5629947.png">

How to fix?

**Comment by CiGit** [comment]
This issue belongs in prettier. see https://github.com/prettier/prettier/issues/1825
