### ISSUE TITLE
(json-to-ast) Cannot Tokenize Symbol </> at (1:1)

### ISSUE THREAD

**Issue by frankhale** [esbenp/prettier-vscode#149]
This issue was originally put in on VS Code but was notified that this is a Prettier issue, reference: https://github.com/Microsoft/vscode/issues/29701

I have format on save set and when I go to try to save changes to my settings.json file I get this error (in title)

Screenshots below:

![27620849-8ebf50c8-5b9a-11e7-9cab-52148d07fb5b](https://user-images.githubusercontent.com/190154/27842053-4032a024-60d4-11e7-8fd5-f404bd83a18f.PNG)

![27620892-d6f0a9b4-5b9a-11e7-8e6b-41882d7318b9](https://user-images.githubusercontent.com/190154/27842055-4766f502-60d4-11e7-99ef-19fec21d01a7.png)

**Comment by frankhale** [comment]
I can only confirm this is happening when saving settings.json (but it may be any .json file)

**Comment by CiGit** [comment]
Yes, this is due to the token at (1:1) `/`
Comments are not part of the JSON spec 😢
Remove the top comment (and any other comment) to fix it.

**Comment by frankhale** [comment]
Yes this definitely works but is this error something new that was added to Prettier because I've never seen it before, well since last week sometime.

**Comment by CiGit** [comment]
This is a week old. Since prettier formats JSON(real json for now) and others: https://github.com/esbenp/prettier-vscode/releases/tag/v0.20.0

**Comment by frankhale** [comment]
@CiGit thanks for clearing up my confusion!

**Comment by jitendravyas** [comment]
I'm also getting this problem. What to do?

**Comment by frankhale** [comment]
Remove anything that doesn't conform to the JSON spec, eg. comments (that's probably what is causing the issue, at least that was what was causing mine)

**Comment by thedamon** [comment]
Is there a way to turn off parsing for particular files or allow non-strict JSON parsing?

**Comment by CiGit** [comment]
For particular files, not yet.
non-strict JSON: not yet.
If you need to format pseudo JSON, IMO the best choice you have is to rely on the default formatter which does it's job.
To do so: empty jsonEnable array.

**Comment by krokofant** [comment]
Related upstream issue https://github.com/prettier/prettier/issues/2378

**Comment by nikitavoloboev** [comment]
Is it still not possible to have prettier ignore formatting settings.json file?

This issue is really annoying and I can't remove the comments from settings as I use them for my personal documentation.

**Comment by krokofant** [comment]
@nikitavoloboev I believe it will be possible with the next prettier release since the fix was committed 7 days ago. No idea when it'll be out though.
