### ISSUE TITLE
Shebangs get removed

### ISSUE THREAD

**Issue by paylesworth** [esbenp/prettier-vscode#15]
Adding a shebang line:
`#!/usr/bin/env node`
gets converted to a comment:
`///usr/bin/env node`
preventing the script from running as a standalone command.

I am using MacOS Sierra with VS Code and the prettier extension.

**Comment by paylesworth** [comment]
Sorry, wrong place. I see it is already posted on the Prettier tracker.

**Comment by esbenp** [comment]
No worries :-)
