### ISSUE TITLE
bracketSpacing option not working

### ISSUE THREAD

**Issue by VMBindraban** [esbenp/prettier-vscode#151]
I noticed that the `bracketSpacing` option is not working.
When setting `prettier.bracketSpacing: false`

```js
function foo({bar}) {
```

becomes:

```js
function foo({ bar }) {
```

When running `prettier-eslint --write --no-bracket-spacing` it does respect the option.

**Comment by CiGit** [comment]
Have you enabled `prettier.eslintIntegration`?

It seems to me prettier-eslint-cli and this extension do not use the parameters the same way.
In this extension, prettier options are fallback in case it is not specified in your eslint config

**Comment by VMBindraban** [comment]
I am a idiot. I was using a different module. I switch to this one and it worked :)
