### ISSUE TITLE
`printWidth` can't be changed

### ISSUE THREAD

**Issue by anhldbk** [esbenp/prettier-vscode#154]
I've tried to modify `prettier.printWidth = 320` (by default, it's set to 80), but it does NOT work as I want

![screenshot from 2017-07-06 15-40-08](https://user-images.githubusercontent.com/3270746/27902852-7144a52a-6261-11e7-99c2-67fbe19c6da6.png)

Would you please let me know how to fix this issue?

**Comment by RobinMalfait** [comment]
It looks like you are editing c++ and header files. Prettier currently works on JavaScript, typescript, css, less, scss and GraphQl.

**Comment by anhldbk** [comment]
@RobinMalfait Thank you! Gonna disable `editor.formatOnSave`

**Comment by RobinMalfait** [comment]
@anhldbk It is vscode or another extension that is formatting your code not prettier. Maybe prettier will have support for c++ one day 😄
