### ISSUE TITLE
The differencies between plugin and command prettier result

### ISSUE THREAD

**Issue by MarcelGeo** [esbenp/prettier-vscode#16]
The source code resulted from Prettier VS Code plugin is different from results of command prettier --write /somefile/*.js . The difference is occured in keys inserted to React Component. This keys are not on newlines in results from plugin. See file with example [testing_prettier.zip](https://github.com/esbenp/prettier-vscode/files/705918/testing_prettier.zip) .

Input file:
testing_prettier.js

Output from plugin:
testing_prettier_afterplugin.js

Output from command:
testing_prettier_aftercommand.js

The keys named key, className and onClick are delimited with new line in result from command, I think that is right.

**Comment by esbenp** [comment]
Hmmm.. Maybe it is because your global version is not the one installed locally by the plugin. #17 updates Prettier to `0.0.7` and was deployed in `0.4.0`. Can you try updating and see if it helps?

**Comment by MarcelGeo** [comment]
Thank you, this helps.
