### ISSUE TITLE
Bring back the old Error notification

### ISSUE THREAD

**Issue by thangngoc89** [esbenp/prettier-vscode#160]
I really missed the old Prettier error notification. Moving the error to a seperate panel make no sense to me since I have to wait for Webpack to compile and tell me where is the error? Or open the panel to see the actually error.

**Comment by CiGit** [comment]
The panel opens on the first error. We removed the popup because it was annoying.
Which errors are you missing?

**Comment by thangngoc89** [comment]
@CiGit I As the panel is on the bottom of the screen, it covers most of my screen so I have to close it anytime it pops up. I'm missing all inline errors report. Not sure if it's relevant but I'm using [Flow integration](https://github.com/flowtype/flow-for-vscode)

**Comment by CiGit** [comment]
You can resize the panel. This panel is quite new, we can iterate a little more on it. But I don't think the popup is a good idea. You may use a linter for those errors which is not prettier's scope (even if prettier needs a valid program to run)
And I would avoid options which are not necessary.

**Comment by RobinMalfait** [comment]
It will also show a status bar item like so: `Prettier: X` when you see it, something is wrong and by clicking on it you can re-open the panel fairly easily. This way you don't have to open panels and go to the correct output panel.

**Comment by thangngoc89** [comment]
@RobinMalfait Yes. I see the Prettier: X. But it's unnoticeable (at least to me, or I just need to change my habit). 

>  by clicking on it you can re-open the panel fairly easily

Is there any keybinding to reopen the panel? I usually don't use the mouse/touchpad when coding. 

@CiGit 

>  You may use a linter for those errors which is not prettier's scope

Good point. I'm using Flowtype so it catches syntax error, but the integration is buggy ATM so I usually reply on prettier to do the syntax error catching

**Comment by CiGit** [comment]
You can use eslint with flow.

**Comment by CiGit** [comment]
Seems to be the wrong solution to a problem. Closing.
