### ISSUE TITLE
Prettier status bar should be hidden for unsupported languages

### ISSUE THREAD

**Issue by szastupov** [esbenp/prettier-vscode#161]
Hi. I like the new error panel but would prefer it to be hidden when I don't work with JavaScript. Currently it's always shown. Maybe this can be solved by bringing back proper activationEvents to package.json?

**Comment by CiGit** [comment]
Yes we could think about it.
>Maybe this can be solved by bringing back proper activationEvents to package.json?

I'd like to do this, but the activation event depends on all `prettier. ...Enable` settings.

**Comment by szastupov** [comment]
Hm, I'm not very aware of vscode api, but can activationEvents and extension.activate be used at the same time? Like, we could fill activationEvents with all supported languages and then do additional check inside activate().

**Comment by CiGit** [comment]
The problem we have is we don't know "all supported languages". Extensions may register their language.

@RobinMalfait Any thought on this?

**Comment by szastupov** [comment]
Yeah, but you're in sync with latest version of prettier, so at least you know what languages this version of prettier supports. Also, does those advanced options are widely used? Because if they're not, then it doesn't worth supporting them :) It's just better to be a nice citizen and provide proper activationEvents, especially if it's visible that plugin is active.

I'm not pushing, just trying to elaborate. I will keep using the extension anyway 😘

**Comment by RobinMalfait** [comment]
I think that we should not rely on those activation events because once the plugin is activated it's activated. Also the "supported languages" is a problem because it is so configurable. What we should do is toggle the the statusbar item.

Question:

- What do you expect when you are working on javascript file and open a yaml file?
  - Do you want to hide the statusbar because it is not a supported language?
  - Do you want to keep it there because you worked in a javascript right before it?

**Comment by szastupov** [comment]
> Do you want to hide the statusbar because it is not a supported language?

Yep, I think that's the desired behaviour. I.e. show only for supported languages, hide when I switch to something else.

**Comment by RobinMalfait** [comment]
In that case the we can't rely on activation events, so we should watch for workspace document changes and toggle the status bar item when the current language is not in your list of enabled languages. @CiGit Do you want me to provide a PR for this?

**Comment by CiGit** [comment]
I'm happy to let you "statusbar" issues :-) (others too)


>Do you want to hide the statusbar because it is not a supported language?
Do you want to keep it there because you worked in a javascript right before it?

Both seems correct behavior to me.
1. Due to it's action (open panel) it may seems relevant to always have that button if there is something in the panel
2. Explicitly tells : Prettier runs here.

**Comment by vvs** [comment]
Hi guys, let me chime it as well, if you don't mind :)

Personally, I find the always-on "Prettier" text on the status bar to be a distraction (and it consumes precious space I use for other purposes). I'd prefer the status bar to contain the prettier-related stuff *only* when the current file is actually supported. Just imagine if other extensions would start adding stuff to the status bar for all types of files, even for unrelated ones, that would be a mess.

Furthermore, if the configuration states that prettier is currently enabled only for JavaScript, then only Javascript files should have the statusbar with "Prettier". 

That's how I use Prettier at the moment: I enabled it only for JavaScript files. All other files, including json, scss, html, are handled by other fomatter (Beautify).

In this setup, I'd prefer to have "Prettier" in the statusbar only for JavaScript and nothing else.

If I wanted to open the "Prettier" error channel, I could do that with "Quick Open" feature quite easily. Not to mention that usually I am interested in the errors only when I am currently formatting the current file, and then I can see the "Prettier" status bar and can click it.

The need to open "Prettier" error channel from other, unrelated files in very low for me. I'd say, non-existent. :)
