### ISSUE TITLE
Parameter for finding custom prettier in local dependencies

### ISSUE THREAD

**Issue by Alphapage** [esbenp/prettier-vscode#164]
Hello,

I forked prettier in a custom directory (ie 'myprettier') and symlink 'myprettier' to the local dependencies.
Is there a config to set, to point to 'myprettier' repo instead of 'prettier' and be able to switch when needed via settings ?

Thank you in advance for your help.

**Comment by CiGit** [comment]
Hi, we have no such thing.
What you can do is change [this line](https://github.com/esbenp/prettier-vscode/blob/master/src/PrettierEditProvider.ts#L136) and replace 'prettier' with 'myprettier', it should work.
