### ISSUE TITLE
Don't use prettier when the project does not contain prettier as a dev dependency

### ISSUE THREAD

**Issue by abs-zero** [esbenp/prettier-vscode#165]
Currently, prettier formats the file even when the project does not have prettier installed as dev dependency. This is most of the time annoying and unintended. It would be great if we could add this feature.

**Comment by RobinMalfait** [comment]
If you did not install prettier as a dev dependency, it will use the prettier version that comes bundled inside the extension. I think your best option is as follows:

If you don't want it, put these values in your workspace settings.json file.

```js
{
"prettier.javascriptEnable": [],

  // Advanced feature. Enable and use typescript parser for those language ids. Restart required
  "prettier.typescriptEnable": [],

  // Advanced feature. Enable and use postcss parser for those language ids. Restart required
  "prettier.cssEnable": [],

  // Advanced feature. Enable and use json parser for those language ids. Restart required
  "prettier.jsonEnable": [],

  // Advanced feature. Enable and use graphql parser for those language ids. Restart required
  "prettier.graphqlEnable": [],
}
```

**Comment by CiGit** [comment]
You may also want to simply disable the extension for a given workspace.
At least with @RobinMalfait 's solution, you can enable selectively which seems to be impossible with extensions.

**Comment by abs-zero** [comment]
Disabling the extension for a given workspace sounds a good idea. Thanks!
