### ISSUE TITLE
[RFC] Enable/disable prettier formatting using status bar

### ISSUE THREAD

**Issue by tberman** [esbenp/prettier-vscode#169]
The Atom prettier integration allows you to tap the prettier notice on the status bar to temporarily enable/disable formatting-on-save. I find it very useful when editing vendored files inside a workspace.

I am happy to play around with an implementation of this as a PR, but before I did I wanted to check to see if it would be something that makes sense and you would be interested in it?

**Comment by CiGit** [comment]
I think such a feature should be another extension. It would allow to toggle any formatter (which relies on formatOnSave) for such use case.
Toggling formatOnSave settings should do the trick. [wokspaceConfiguration.update](https://code.visualstudio.com/docs/extensionAPI/vscode-api#_a-nameworkspaceconfigurationaspan-classcodeitem-id889workspaceconfigurationspan)
For prettier, a '.prettierignore' should be provided soon. prettier/prettier#2412
This prevents the formatting of specified files.

**Comment by tberman** [comment]
Great call, thanks for the advice.

**Comment by Tom-Bonnike** [comment]
Hey, I just published that extension: https://marketplace.visualstudio.com/items?itemName=tombonnike.vscode-status-bar-format-toggle

**Comment by gabrielmicko** [comment]
@Tom-Bonnike life saver, thanks!
