### ISSUE TITLE
Extension not falling back to bundled prettier on windows

### ISSUE THREAD

**Issue by azz** [esbenp/prettier-vscode#174]
A colleague at work today asked me for help with this extension. Format wasn't working at all (not on save or Format Document). There were no error messages and the Prettier output panel was not present. This happened on Windows 10 and persisted past reinstalling the extension.

Turned out that prettier wasn't installed locally (running `yarn` fixed it), but to my knowledge the extension should notify and fallback to the bundled version of prettier (1.5.2) when no local package is found.

Either way there is a UX problem. I'd expect an error message upon the format comment being invoked.

Unable to provide detailed reproduction steps unfortunately.

Config was just:

```json
{
  "editor.formatOnSave": true,
  "prettier.tabWidth": 4
}
```

We only tried formatting TypeScript files.

**Comment by azz** [comment]
Another piece of information that might help: after running `yarn` there was no need to reload vscode, the extension started working again.

**Comment by CiGit** [comment]
Thanks for the report.
>to my knowledge the extension should notify and fallback to the bundled version of prettier (1.5.2) when no local package is found.

Not exactly, only when it was not declared. I've the guilty [piece of code](https://github.com/esbenp/prettier-vscode/blob/master/src/requirePkg.ts#L34-L37)
If it was declared in package.json we use it. Without checking if it was installed.
Dev console should be red at that point but we don't notify the user. Something we should do. And fallback to bundled prettier.

**Comment by azz** [comment]
Oh, cool. Just needs some `safeExecution`?

**Comment by CiGit** [comment]
I think so, around line 35 as requiring something which doesn't exist crashes. 'Cannot find module prettier' or something like that.
Sorry, I've no debugger right now

**Comment by CiGit** [comment]
Oh and maybe not safeExecution, It supposes a filePath :)
Better try catch{addToOutput(damn); return require('prettier')}
