### ISSUE TITLE
Usage with GraphQL template strings.

### ISSUE THREAD

**Issue by julienvincent** [esbenp/prettier-vscode#176]
This is a bit of a long shot.

Prettier does offer `GraphQL` language support - do you think it would be possible to somehow apply this to template strings within `.js` files?

This might not be the right place to ask this question.  Should I open this on the prettier repo?

**Comment by CiGit** [comment]
It seems to me it already does for tagged template 
[`gql`](https://prettier.io/playground/#%7B%22content%22%3A%22gql%60%7B%5Cn%20%20hero%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7B%5Cn%20%20%20%20%20name%5Cn%20%20%20%20%20%20%20%20%20%20height%5Cn%20%20%5Cn%20%20%7D%5Cn%7D%60%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D)

**Comment by julienvincent** [comment]
Ah! Very cool, I did not notice this, thanks

**Comment by xereda** [comment]
@julienvincent @CiGit 
But how do I add support for the gql tag in vscode? If I simply use it in .js, the validation will be done, stating that the gql is not defined.

**Comment by xereda** [comment]
a related issue:

https://github.com/prettier/prettier-vscode/issues/742
