### ISSUE TITLE
Status bar: Move "Prettier" from left to right

### ISSUE THREAD

**Issue by vvs** [esbenp/prettier-vscode#178]
I think it would be nice to be consistent with other extensions, and move "Prettier" to the right.

Here's how it is now:
![prettier](https://user-images.githubusercontent.com/9781/28531060-f186913e-7095-11e7-86b0-69eed0755086.png)

**Comment by RobinMalfait** [comment]
What are your thoughts on this one @CiGit ?

**Comment by CiGit** [comment]
I'm still searching it on the right side :-) Certainly still used to eslint being on the right side. [this](https://github.com/esbenp/prettier-vscode/pull/152#issuecomment-313204170) was my first impression.

I think, for consistency, it could be on the right side, even if I think we can get used to it.

**Comment by RobinMalfait** [comment]
@CiGit I'm working on a PR to fix #161 maybe I can include this? Like adding it to the right side?
