### ISSUE TITLE
How to block automatic new line creation?

### ISSUE THREAD

**Issue by damienleroux** [esbenp/prettier-vscode#183]
Hello.

When I wrote 

```javascript
			<table>
				<tbody>
					<tr>{upCells}</tr>
					<tr>{valueCells}</tr>
					<tr>{downCells}</tr>
				</tbody>
			</table>
```

prettier transforms it into:

```javascript
			<table>
				<tbody>
					<tr>
						{upCells}
					</tr>
					<tr>
						{valueCells}
					</tr>
					<tr>
						{downCells}
					</tr>
				</tbody>
			</table>
```

How to block prettier from creating new line?

Thank a lot

**Comment by CiGit** [comment]
This is not something we can't control.
But, there are some changes coming for JSX in next prettier version. https://github.com/prettier/prettier/pull/2442

**Comment by damienleroux** [comment]
Yes that works only if there is no other inclusion of tags in the jsx. I mean:

`<span>{test}<span>` stays inline but `<div><span>{test}<span></div>` doesnt and render:

```
<div>
    <span>
        {test}
    <span>
</div>
``` 

Anyway I close the issue, I finally use only the default vscode formatter avtivating the vscode option `"editor.formatOnSave": true`.

Thank you for your time.
