### ISSUE TITLE
single char with single quotes

### ISSUE THREAD

**Issue by damienleroux** [esbenp/prettier-vscode#184]
Hello.

Prettier autoformats `'/'` to `"/"`.

It make more sens for me than single char should have single quotes.

How to control when using single quotes or double quotes?.

Thank you for your help

**Comment by CiGit** [comment]
There is an option for **strings** `singleQuote:boolean`
But if I understand correctly you would like to have something like:
```js
const URI = "root" + '/' + "path"
```
There are no options to do so. It seems to me eslint has no such options either.

IMHO this is misleading as there is no `char` type in javascript. They all have the same type (`string`)

**Comment by RobinMalfait** [comment]
There might be confusing with the `Java` programming language where `'/'` is a char and `"/"` is a string (array of chars). But like @CiGit said in JavaScript they are all `string` types.

**Comment by damienleroux** [comment]
ok thank you for the explanation
