### ISSUE TITLE
Seems to not respect the Prettier's resolving of config files?

### ISSUE THREAD

**Issue by charlike** [esbenp/prettier-vscode#185]
I just tried to remove all the my user preferences from the VSCode's `settings.json` and set it to `.prettierrc.json` and seem it not work.

Actually it has splashes, similar to what it was with raw eslint + raw prettier, before `prettier-eslint` comes to the world. I must click `ctrl+s` (autofix/autoformat on save) 2 times.

**Comment by CiGit** [comment]
For the first part, we don't read `.prettierrc.json`. We will read from file system #167, but that file doesn't belong to the list anyway.

I don't get the second part of your issue. Without settings it should be default settings.

**Comment by charlike** [comment]
> We will read from file system #167, but that file doesn't belong to the list anyway.

Prettier uses `cosmiconfig` so it reads it both `.prettierrc.json` and `.prettierrc.yaml` too. So it should support it.

> I don't get the second part of your issue. Without settings it should be default settings.

Actually yea, that's the problem: that it currently does not reads Prettier's config files. The WIP PR seems okey, just need to add both `.json` and `.yaml` files too. :)

Okey, anyway. Please ping me, if you can, when release with that merge is published :) :wave:

**Comment by CiGit** [comment]
> Prettier uses cosmiconfig so plugin should read it both .prettierrc.json and .prettierrc.yaml too.

This is not the case. By default (which is prettier's choice)
> For example, if your module's name is "soursocks," cosmiconfig will search out configuration in the following places:
a soursocks property in package.json (anywhere down the file tree)
a .soursocksrc file in JSON or YAML format (anywhere down the file tree)
a soursocks.config.js file exporting a JS object (anywhere down the file tree)
a CLI --config argument

> Please ping me, if you can, when release with that merge is published :)

I dont' think I will remember. The best choice you have is: track updates on #167. Once merged, release will follow under a day. And probably under an hour.

**Comment by charlike** [comment]
Oh, probably I didn't said it good :D 

> By default (which is prettier's choice)

yes, exactly. I just meant that you should follow Prettier 1:1 and look for everyone of these config places. (I'm saying that, because didn't see them in the PR suggestion)

**Comment by CiGit** [comment]
And https://github.com/prettier/prettier/pull/2434 is what prettier implements ;-)
Ask @azz for it :-)

**Comment by charlike** [comment]
I don't have anything to ask anyone ;d I'm just saying that that integration should follow Prettier defaults, no matter how. :wave:

**Comment by azz** [comment]
I'm confused. This extension doesn't look for config files, it asks (or more accurately, will ask, the feature isn't released) prettier to find a config file, so by definition it follows "prettier defaults".

Prettier also uses cosmiconfig defaults, which means `.prettierrc.json` files are *not* supported. If you have a strong use case for such a format, please open an issue with prettier itself.

**Comment by charlike** [comment]
Oh was tired yesterday. Looking closing in `cosmiconfig` readme clears the situation. I'll try just `.prettierrc` without extension ;d Sorry :v:
