### ISSUE TITLE
Add prettier.formatOnSave option

### ISSUE THREAD

**Issue by bjudson** [esbenp/prettier-vscode#186]
I have Python & JavaScript code in the same project, and would like to use Prettier for JS, but am not really happy with Python code formatting options at this point. Since both Prettier and [Python plugin](https://github.com/DonJayamanne/pythonVSCode) respect `editor.formatOnSave`, I can't selectively turn on formatOnSave for Prettier only (the Python plugin does a bunch of stuff other than formatting which I need in my project). Adding a plugin-specific option for this would solve the problem.

**Comment by RobinMalfait** [comment]
Python is not supported by prettier currently, so you probably want to disable the other plugin instead. Apart from that you can use language specific settings in VScode. Currently on my phone so let me try to find info

**Comment by RobinMalfait** [comment]
https://github.com/esbenp/prettier-vscode/issues/182#issuecomment-318410292

**Comment by bjudson** [comment]
Ah, the language-specific setting was exactly what I needed! Thank you so much. If anyone stumbles on this, I now have:
```
{
  "editor.formatOnSave": false,
  "[javascriptreact]": {
      "editor.formatOnSave": true
  }
}
```

**Comment by SupriyaKalghatgi** [comment]
@bjudson I tried with the above snippets in `settings`
dd'nt work for me

**Comment by CiGit** [comment]
`javascriptreact` is for jsx files. Out of the box at least.
`javascript` should match js files.
