### ISSUE TITLE
Quote rules responding unexpectedly on auto save. (Single and double quotes)

### ISSUE THREAD

**Issue by the-simian** [esbenp/prettier-vscode#187]
When I use the prettier plugin, I am experiencing some abnormality with the format on save feature and quotes, I'll try my best to show you what I am describing:

Given the following eslint
```
{
	"plugins": [ "prettier" ],
	"parser": "babel-eslint",
	"rules": {
		"prettier/prettier": [
			"error",
			{
				"singleQuote": true
			}
		]
	}
}
```
So this is prettier (out of the box) the only change is I am intentionally using doulbe quotes.

In the project I might come across this: 
![image](https://user-images.githubusercontent.com/954596/28757721-c740c53a-754e-11e7-879d-862abb27adf8.png)
Here prettier vs code extension has detected the rule, and even has the handy autofix capability.

However herein lies the problem:
If I set this property in visual studio:
// Place your settings in this file to overwrite the default settings
```
{
    "editor.formatOnSave": true
}
```
The editor will always revert the quotes to double every time, which means I basically fix, and fight my editor every save.

I looked around and saw another person also experienced this: 
https://stackoverflow.com/questions/45124451/prettier-doesnt-work-for-changing-double-quote-to-single-quote-in-visual-code

If I am overlooking an obvious configuration step, let me know.

**Comment by RobinMalfait** [comment]
Do you have other plugins running which are doing a format on save? Can you share your settings.json file from VScode?

**Comment by CiGit** [comment]
Note: this extension has **no** auto-fix. This is most likely eslint extension.
And It seems to me prettier-eslint doesn't read from _prettier/prettier_ plugin

**Comment by the-simian** [comment]
@RobinMalfait The only overridden property in the settings.json was the one property I had posted, but since reverted due to the conflict
```
{
    "editor.formatOnSave": true
}
```
see:
![image](https://user-images.githubusercontent.com/954596/28806317-f068e000-7634-11e7-8b40-dae5203c7b53.png)

@CiGit 
I have exactly 3 extensions installed at the moment:
- EsLint
- Prettier
- sort-imports
![image](https://user-images.githubusercontent.com/954596/28806363-29d3c756-7635-11e7-80fc-a89204932839.png)

I already posted the entirety of my .eslintrc file, but to be clear this is it:
```
{
	"plugins": [ "prettier" ],
	"parser": "babel-eslint",
	"rules": {
		"prettier/prettier": [
			"error",
			{
				"singleQuote": true
			}
		]
	}
}
```
![image](https://user-images.githubusercontent.com/954596/28806389-5f01c022-7635-11e7-96fc-7cf4795426a4.png)


Do you believe there is a plugin conflict?

**Comment by the-simian** [comment]
Edit: This is definitely a side effect of using both prettier and eslint simultaneously. using one or the other doesn't cause the problem to occur , yet nor does it autoformat the code quotes specifically on save. Either you go with double quotes, and things also fix on save, or you can have single quotes, but you must use the autofix command, and disable fix on save.

Not 100% sure how to fix this atm, sorry I could not add more useful info to troubleshoot. Appreciate all help thusfar. :)

**Comment by RobinMalfait** [comment]
You have to enable eslint integration in your settings like this:

```json
"prettier.eslintIntegration": true
```

**Comment by CiGit** [comment]
> Fix this prettier/prettier problem 

This is from eslint. Your prettier/prettier rule from `eslint-plugin-prettier`.
You have too much prettier in your workflow. `eslint-plugin-prettier` already runs prettier with it's settings. You specified `singleQuote:true`.
If you use this extension, you are running prettier with `singleQuote:false`, the default.
If you use this extension's settings `prettier.eslintIntegration:true` it will read your eslintrc file and infer the singleQuote option. **BUT** from `quotes` rule not from `prettier/prettier:[{singleQuote}]`. We use prettier-eslint under the hood.

eslint-plugin-prettier is usefull to have eslint in control with prettier under the hood.
eslint-config-prettier disables eslint's styling rules. And you can use prettier for that.

**Comment by joelhulen** [comment]
Just modify your user preferences in VSCode to this:
`"prettier.singleQuote": true`
