### ISSUE TITLE
Configure which file extensions should be processed

### ISSUE THREAD

**Issue by iambrandonn** [esbenp/prettier-vscode#32]
I've noticed that with `formatOnSave` as true all files are run through prettier, whether they are js, html, svg, etc...
I would like to be able to configure which extensions are and are not processed.

**Comment by vasa-chi** [comment]
I've made a PR #31 to make prettier to run only on javascript files. Waiting for response from author :)

**Comment by CiGit** [comment]
#31 was closed in favor of #18. It runs only on javascript, javascriptreact files (.js, .jsx)

**Comment by li-xinyang** [comment]
I am using the lastest version of `Prettier` and it is still formating `*.hbs` file on save

**Comment by CiGit** [comment]
It certainly is some other formater.
trying to format your code with prettier will throw: `Unexpected character '#' `

**Comment by li-xinyang** [comment]
I'm posting here becase `prettier-vscode` is the only formater I installed on my machine. Not sure where the default famator come from

**Comment by CiGit** [comment]
From vscode I think. You can run `code --disable-extensions ` to be sure.

**Comment by sgwatgit** [comment]
I think the issue people are experiencing is they want prettier to run on save for their .js/.jsx/.ts/.tsx but they don't want format on save for their .html files.

As can be seen in this comment for the vscode issue about language specific settings https://github.com/Microsoft/vscode/issues/1587#issuecomment-273746046 you can do something like

```
"[typescript]": {
      "editor.formatOnSave": true
}
```

which will allow for saving typescript files to format with prettier but html files won't be formatted on save. :)

**Comment by halvard-cognite** [comment]
For an easy copy paste for others:

If you want to just disable formatting for .hjs

```json
  "[handlebars]": {
    "editor.formatOnSave": false
  }
```
