### ISSUE TITLE
What are the rules around what prettier version is used?

### ISSUE THREAD

**Issue by jonathaningram** [esbenp/prettier-vscode#33]
If I run `prettier` from the version installed in my project (from `npm install --save-dev prettier`), the output is different to that of the VS Code extension. I can see that the prettier version in the extension is fixed.

1. Is it possible for the extension to use the local `prettier` if it exists instead of the one it provides?
2. If not, is it possible to update the `prettier` version in this extension and if so, are you just going to have to manually update it all the time when a new `prettier` comes out?

Thanks for the great extension.

**Comment by CiGit** [comment]
It should be possible to modify the extension to use a local version. I would even add a globally installed one.
1. use local version
1. use global version
1. use packaged version: Works out of the box and everyone can't sudo or have a local version. This one needs to be updated in the extension itself.

I think it is possible to update the dependency by going into vscode's extension folder, find this extension and `npm i prettier@latest`. Restart vscode.

I expect prettier to have a lot less updates in the future, it is really new and will likely stabilize. The global version I mentioned might not be necessary (SOON)

**Comment by jonathaningram** [comment]
Great I'll try it out. I'll close this in favour of #29 (which I did not see). Thanks @CiGit
