### ISSUE TITLE
Bracket Spacing not respecting []

### ISSUE THREAD

**Issue by michaelryancaputo** [esbenp/prettier-vscode#35]
Before upgrade to 0.7.0, brackets would be spaced: `[ 'value' ]` now they do not allow spacing: `['value']`.

It still respects {}, but not square brackets :(

**Comment by esbenp** [comment]
Are you sure this issue is not related to [prettier itself](https://github.com/jlongster/prettier)? 0.7.1 bumped Prettier from `0.11.0` to `0.15.0`

**Comment by CiGit** [comment]
It was changed in jlongster/prettier#446

**Comment by esbenp** [comment]
Thanks @CiGit

**Comment by michaelryancaputo** [comment]
Thank you.
