### ISSUE TITLE
Flow parser removes line breaks

### ISSUE THREAD

**Issue by zoontek** [esbenp/prettier-vscode#46]
Hello,

I would like to know if it's actually possible to disable this extensions for certains files? Like the JSON ones. Maybe by using a glob in settings.

**Comment by CiGit** [comment]
There is currently no option to disable it for some file pattern.

The extension does not run on JSON *language*, it runs on javascript and javascriptreact as specified [here](https://github.com/esbenp/prettier-vscode/blob/418ae37a055c815b8fb60148f9f6614d2e85df28/src/extension.ts#L10)
Prettier throws an error on JSON object files and thus, the extension shouldn't do anything (a log in the developer tool)

Is this issue about JSON betting prettified or about a feature request?

**Comment by zoontek** [comment]
It performs on JSON and sometimes on certain JS files, by removing empty lines breaks, which is super annoying :(

JS file:
![](http://g.recordit.co/bz9C2xCd59.gif)

JSON file:
![](http://g.recordit.co/xedoLqVbtt.gif)

**Comment by CiGit** [comment]
Do you have any other formatter installed (extension)? prettier does not remove single line breaks like on your JS file.

For the JSON file, removing lines is the behavior of vscode's embed formatter.

**Comment by zoontek** [comment]
I don't think. `editor.formatOnSave` is set to `true`, and when prettier-vscode is disabled, it doesn't do that. Very strange.

**Comment by CiGit** [comment]
About which file type are you speaking? Both?
Just to be sure about your JSON file. If you set `"json.format.enable": false,` in your settings, does it still happen ? This is the embed json formatter.

Can you try prettier@0.21.0 with the command line on your JS file? 

Can you also test with all extensions disabled but prettier ?

I'm unable to reproduce your problem with the JS file. With the JSON file I think this is the embed formatter.

**Comment by zoontek** [comment]
`"json.format.enable": false` does the trick for the JSON files 👍 
I disable every extensions except this one, and still encounter the problem. But it doesn't appear when I use the babylon parser (only appear with the flow parser)

**Comment by CiGit** [comment]
Still seems there is an issue tho. I cannot reproduce this issue with the flow parser and a minimal code. Is it possible for you to provide a minimal code which produce this error and your settings for prettier. 
Note: I also tried with `CRLF`

**Comment by zoontek** [comment]
I isolate the bug. Here is the minimal setup to reproduce it:

```js
// @flow

import React, { Component } from 'react';
import { connect } from 'react-redux';
import { t } from '../utils/i18n';

class MyClass extends Component {
  render() {
    return (
      <span>
        {t('price info', { price: '8€' })}
      </span>
    );
  }
}
const mapStateToProps = (state, ownProps) => ({
  navigation: ownProps.navigation,
});
const mapDispatchToProps = (dispatch, ownProps) => ({});
export default connect(mapStateToProps)(MyClass);
```

It doesn't happen if I remove the `€` character, and seems not related to this plugin (does the same using prettier directly). I should create an issue on the prettier repo.

**Comment by zoontek** [comment]
No need, I found one: https://github.com/prettier/prettier/issues/770
