### ISSUE TITLE
Option to indent with tabs

### ISSUE THREAD

**Issue by Hargne** [esbenp/prettier-vscode#47]
Thanks for a superb plugin! 
What our team is looking for is an option to select either to indent with spaces or tabs. 
I am fully aware of the Spaces vs Tabs war, but the option to select one of them would be awesomeness!

Thanks!

**Comment by CiGit** [comment]
Prettier currently does not support tabs. But we will provide an option for that once :question: prettier supports it.
There is an issue about that in prettier/prettier#908

**Comment by esbenp** [comment]
Closed in favour of prettier issue

**Comment by rhengles** [comment]
There is also https://github.com/passionkind/prettier-vscode-with-tabs

**Comment by CiGit** [comment]
@rhengles I see a fork without any change. Do I miss something?

**Comment by passionkind** [comment]
now there are changes... 🙈

**Comment by passionkind** [comment]
@esbenp please let me know in case you want me to change anything to clearly point out that you're the original author

**Comment by esbenp** [comment]
It is completely fine with me :-)
