### ISSUE TITLE
can't get this to work

### ISSUE THREAD

**Issue by pekeler** [esbenp/prettier-vscode#51]
Installed with VSCode 1.9.1 on Ubuntu, reloaded, CTRL-SHIFT-P brings up VSCode's command palette, it doesn't format the code. Typing "prettier" in the command palette doesn't bring up anything. VSCode's Problems and Output panes don't show anything about Prettier, either.

Exact same problem with VSCode 1.10.2 on Mac OS. I've been using other VSCode plugins like Standard without problem. What's the trick to get prettier-vscode working?

Also, CMD-SHIFT-P is by default mapped to the command palette. Why use this for formatting?

**Comment by pekeler** [comment]
<img width="872" alt="prettier" src="https://cloud.githubusercontent.com/assets/42363/24021165/2973a9de-0a65-11e7-8e00-da453ed7e436.png">
<img width="384" alt="cmd-shift-p" src="https://cloud.githubusercontent.com/assets/42363/24021227/7869a35e-0a65-11e7-8836-d1c6606a3fc0.png">

**Comment by dKab** [comment]
Same here. My OS  - Ubuntu

**Comment by CiGit** [comment]
It is bound to `Format Document` in Command palette. `CTRL+SHIFT+I` by default on Linux

**Comment by pekeler** [comment]
Ahhh, that works. And ALT-SHIFT-F on the Mac. Thank you @CiGit!
Is CMD-SHIFT-P for Windows?

**Comment by dKab** [comment]
@CiGit any idea why when I format document with ctrl+ shift +i the formatting differs from when I format the same document via prettier CLI with --write? @pekeler could you check this on your linux setup, too?

**Comment by CiGit** [comment]
@pekeler Windows: `SHIFT+ALT+F` by default

---
@dKab It may be:
* Different config
* Different prettier version (latest prettier-vscode is based on 0.22.0)
* Additional vscode plugin which also transforms your code.

I'll close that issue. It has been answered and the [README](https://github.com/esbenp/prettier-vscode/blob/0.10.1/README.md#usage) mentions it.
@dKab Please open a new issue if needed

**Comment by dKab** [comment]
The same on Windows 10. I use [eslint-plugin-prettier](https://github.com/not-an-aardvark/eslint-plugin-prettier) with [eslint-config-prettier](https://github.com/prettier/eslint-config-prettier) and when I format document from vscode command palette (which you are saying invokes prettier when your extension is enabled) eslint still shows errors. However when I run prettier from command line eslint is silent.

**Comment by Maxhodges** [comment]
I installed Prettier and restarted, but there is no `>Format Document` command. OSX. option + shift + F works, but think it's using the Visual Code default formatter.. 

![image](https://user-images.githubusercontent.com/957271/29002308-4a2a409e-7ada-11e7-86e8-fa170cb83908.png)

**Comment by RobinMalfait** [comment]
This plugin registers itself as a formatter. Therefore it works using the built in `Format Document`

**Comment by Maxhodges** [comment]
OK, thanks

**Comment by dongcai** [comment]
> Ahhh, that works. And ALT-SHIFT-F on the Mac. Thank you @CiGit!
> Is CMD-SHIFT-P for Windows?

ALT-SHIFT-F  for Mac. Why not update the Readme?
