### ISSUE TITLE
Results are different for prettier-vscode and prettier CLI

### ISSUE THREAD

**Issue by dKab** [esbenp/prettier-vscode#52]
I have prettier v0.22.0 installed locally in my project. When I use it from command line output differs from what I get when I do Format Document from command palette. 
I do not have any other formatting extensions installed and I use default options for prettier.
 
![image](https://cloud.githubusercontent.com/assets/6264291/24035539/fa875c9a-0b06-11e7-8449-250a49e4ea5b.png)

**Comment by CiGit** [comment]
Can you provide a minimal code example which shows this difference ?

**Comment by dKab** [comment]
The output of Format Document:
```
export default store => next => action => {
  const callAPI = action[CALL_API];
  if (typeof callAPI === "undefined") {
    return next(action);
  }

  const { endpoint, types } = callAPI;

  if (typeof endpoint !== "string") {
    throw new Error("Specify a string endpoint URL.");
  }
  if (!Array.isArray(types) || types.length !== 3) {
    throw new Error("Expected an array of three action types.");
  }
  if (!types.every(type => typeof type === "string")) {
    throw new Error("Expected action types to be strings.");
  }

  const actionWith = data => {
    const finalAction = { ...action, ...data };
    delete finalAction[CALL_API];
    return finalAction;
  };

  const [requestType, successType, failureType] = types;
  next(actionWith({ type: requestType }));

  return callApi(endpoint).then(
    response => next(
      actionWith({
        response,
        type: successType
      })
    ),
    error => next(
      actionWith({
        type: failureType,
        error: error.message || "Something bad happened"
      })
    )
  );
};
```
The output of `prettier --write`:
```
export default store =>
  next =>
    action => {
      const callAPI = action[CALL_API];
      if (typeof callAPI === "undefined") {
        return next(action);
      }

      const { endpoint, types } = callAPI;

      if (typeof endpoint !== "string") {
        throw new Error("Specify a string endpoint URL.");
      }
      if (!Array.isArray(types) || types.length !== 3) {
        throw new Error("Expected an array of three action types.");
      }
      if (!types.every(type => typeof type === "string")) {
        throw new Error("Expected action types to be strings.");
      }

      const actionWith = data => {
        const finalAction = { ...action, ...data };
        delete finalAction[CALL_API];
        return finalAction;
      };

      const [requestType, successType, failureType] = types;
      next(actionWith({ type: requestType }));

      return callApi(endpoint).then(
        response =>
          next(
            actionWith({
              response,
              type: successType
            })
          ),
        error =>
          next(
            actionWith({
              type: failureType,
              error: error.message || "Something bad happened"
            })
          )
      );
    };
```

Note how in the latter snippet 
`export default store => next => action => {`
becomes splitet on several lines:
```
export default store =>
  next =>
    action => {
```

**Comment by CiGit** [comment]
On your screenshot, in vscode's settings, the left part shows the default settings. Yours are on the right ;-)

**Comment by dKab** [comment]
@CiGit Yeah, sorry, you are right. There's nothing there related to prettier though...

**Comment by CiGit** [comment]
Was just to be sure.
I've a minimal reproduction on my side
```javascript
s =>
  a => {
    let v;
  };
```

**Comment by CiGit** [comment]
```js
(s => a => {
  let v;
});
```
is the output of prettier 0.21

The extension is bundled with prettier@0.21
```sh
$ cat extensions/esbenp.prettier-vscode-0.10.1/node_modules/prettier/package.json| grep '"version":'
  "version": "0.21.0"
```
@esbenp You will have to republish `npm install` before ;-)

**Comment by dKab** [comment]
So how does this work? Will extension update itself every time new version of prettier is released? Are you required to manually republish extension on every prettier release?

**Comment by CiGit** [comment]
Currently something like that. I don't know if @esbenp has a little script on his side.
We have #39 awaiting to be able to use prettier from the workspace.

**Comment by esbenp** [comment]
Good news I have just published #39 which should enable VS Code to use the projects Prettier

**Comment by esbenp** [comment]
https://github.com/esbenp/prettier-vscode/releases/tag/0.11.0

**Comment by esbenp** [comment]
@dKab please let us know if this resolves your issue :-)

**Comment by dKab** [comment]
Do I need to do anything with the extension? I  mean uninstall/install in order to get this fix?

**Comment by esbenp** [comment]
If you go to the extensions pane it should tell you that it has a new version

**Comment by dKab** [comment]
@esbenp It works now, thanks!
