### ISSUE TITLE
Trailing commas setting does not work

### ISSUE THREAD

**Issue by markbrouch** [esbenp/prettier-vscode#54]
Using `v0.11.0` trailing commas are always added, even when User Settings or Workspace Settings contains `"prettier.trailingComma": "none"`.

**Comment by markbrouch** [comment]
Update - issue was I had an old version of `prettier` installed in `node_modules`. Is there a way to override the extension so that it uses the version of `prettier` installed with the extension instead of the project?

**Comment by jupiterzzz** [comment]
I got the "Validation Error" Issue when I installed 0.11.0 version of this extension.
I found a workaround for this, by installing 0.10.1 version from URL:

https://esbenp.gallery.vsassets.io/_apis/public/gallery/publisher/esbenp/extension/prettier-vscode/0.10.1/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage

**Comment by CiGit** [comment]
@markbrouch it's not possible to use the bundled version over the project one. I'm curious, why would you prefer to use a different version from the project one?

@jupiterzzz What do you mean by *Validation Error* ?

**Comment by gusvargas** [comment]
I was on `prettier@v0.17.1` and after upgrading to the latest `prettier-vscode` formatting stopped working completely. After upgrading my local prettier to `0.22.0` it all started to work again as expected.

@CiGit I also experienced what @jupiterzzz described – after upgrading `prettier-vscode` while on an old version of `prettier` VSCode would a generic looking "Validation Error" banner with no context as to what caused the error – it was strange. Still not sure what caused the error but again, upgrading local `prettier` seemed to resolve the issue.

**Comment by CiGit** [comment]
Found out the *Validation Error* problem. The hidden message is 
``` 
Option "trailingComma" must be of type:
    boolean
  but instead received:
    string

  Example:
  {
    "trailingComma": false
  }

```
This is due to how we handle settings and the trailing comma change between different versions.
By default we pass in `"none"`. Prettier 0.19.0 changed this option from a boolean value to a string value. It may be possible to set your setting explicitly to `true`/`false` if you really want to use a version older than 0.19.0.

**Comment by markbrouch** [comment]
@CiGit good point - don't really need to use different version than what's in project. Just had a weird circumstance where I couldn't update project right away but wanted to try out a newer version of Prettier.

**Comment by esbenp** [comment]
We should close this in favour of #55, yeah? @CiGit

**Comment by CiGit** [comment]
Seems fair enough
