### ISSUE TITLE
TSX falls back to JS

### ISSUE THREAD

**Issue by madslundt** [esbenp/prettier-vscode#58]
TypeScript React falls back to JavaScript. It would be better to fall back to JSX (JavaScript React).

**Comment by CiGit** [comment]
:confused: Can you explain a little more what you mean ?
Prettier doesn't handle typescript.

**Comment by madslundt** [comment]
Yes sorry.

The problem is when formatting the document, using TSX, it formats the document like it was just vanilla JavaScript (I suppose). This make the types and interfaces fly around and doesn't look so good.

Example using TSX:
`export class Todo extends React.Component <void, TodoState>`
is formatted into
`export class Todo extends React.Component < void,
TodoState >`

**Comment by CiGit** [comment]
This extension runs on Javascript and Javascript React. Have you (or any of your extension) set `tsx` files to be any of those two? I'm asking because I see a line break and I'm pretty sure the provided typescript formater doesn't insert those. Any other formatter installed ?

**Comment by esbenp** [comment]
@CiGit is it not because the extension only activates on `javascript` and `javascriptreact`? When doing typescript react I think VS Code sets the language to `typescriptreact` or something similar. So I think we just need to add that as a valid language

**Comment by CiGit** [comment]
We currently can't activate it on typescript. There is a WIP PR on prettier to be able to parse/print typescript.
