### ISSUE TITLE
Blank validation error when using "editor.formatonsave": true

### ISSUE THREAD

**Issue by marcpechaitis** [esbenp/prettier-vscode#59]
Hi I get the following blank error when I save file with `"editor.formatonsave": true`

![screen shot 2017-04-03 at 1 06 06 pm](https://cloud.githubusercontent.com/assets/12177541/24626452/93ea8a64-186e-11e7-9f43-a5b1fbfee611.png)

These are the settings I am currently using:
`{
    "editor.cursorStyle": "line-thin",
    "editor.cursorBlinking": "phase",
    "editor.minimap.enabled": true,
    "editor.formatOnSave": true,
    "flow.useNPMPackagedFlow": true,
    "javascript.validate.enable": true,
    "prettier.parser": "flow",
    "prettier.singleQuote": true,
    "terminal.external.osxExec": "iTerm.app",
    "workbench.colorTheme": "Material Theme",
    "workbench.iconTheme": "vscode-icons"
}`

When I disable `edit.formatonsave` I do not get the error drop down in my screenshot, but of course it does not format the code, either.

Can anyone provide insight into what I might be doing wrong?

**Comment by CiGit** [comment]
We currently have a problem with those kind of errors #55 .
It seems to be a problem with our settings and prettier's version you are using.
Do you have any `prettier@ < 0.19` installed locally? 
You can also see the complete error message in `Help -> Toggle Developer Tools`

**Comment by marcpechaitis** [comment]
Thank you @CiGit.

I have Prettier 0.22.0 installed locally.

I used the `Help -> Toggle Developer Tools` and confirmed the error message is the same "trailingComma" error per [#54](https://github.com/esbenp/prettier-vscode/issues/54) and [#55](https://github.com/esbenp/prettier-vscode/issues/55)

**Comment by CiGit** [comment]
If it uses Prettier 0.22 it should yell for those trailingComma. By default we pass 'none' in which is valid for that Prettier version.
I'm confused, your settings seems fine regarding `trailingComma`.

**Comment by marcpechaitis** [comment]
Update:  
I checked that the version of Prettier in the package.json was `^0.18.0`, but I also have it installed globally at `0.22.0`.  Confirmed (via `which prettier`) that it was using the global version.

I changed the version in my package.json to `^0.22.0`, ran `npm update`, closed VSC and after re-opening my problems went away.  (I'm not sure if all those steps are necessary or proper...still trying to grok it all!).  Is it possible that the `^0.18.0` version in package.json was throwing it off?

**Comment by CiGit** [comment]
This extension doesn't make use of your global installed prettier. By *local* I was meaning one lying in a `node_modules` on the path to your file. Exactly the same prettier as if you would `require("prettier")` from your file.
You have to at least `reload window` for this extension to pick the new version up. Previous version was cached by node.
