### ISSUE TITLE
Error : Cannot find module 'jest-validate'

### ISSUE THREAD

**Issue by jetmirshatri** [esbenp/prettier-vscode#60]
Hi everyone! 

I'm using the latest version of `Prettier - JavaScript formatter` on macOS and running VsCode `version 1.11.0` (Insider). I really like this plugin a lot and depend pretty heavy on it but it just stopped working a few days ago. Every time I wanna make use of this plugin I get the following error : 

<img width="1014" alt="screen shot 2017-04-04 at 09 31 09" src="https://cloud.githubusercontent.com/assets/23201486/24645695/8f986106-1919-11e7-98ab-ed9ed59e4003.png">

Here is the complete error message shown in the console:

<img width="1000" alt="screen shot 2017-04-04 at 09 34 14" src="https://cloud.githubusercontent.com/assets/23201486/24645787/ece93f74-1919-11e7-8971-adb8525833bd.png">

I haven't installed any new extensions recently nor have I made changes to my `settings.json`file.

Here are the settings I use for prettier :
`"prettier.printWidth": 100,
  "prettier.singleQuote": true,`

If I **disable** `Prettier - JavaScript formatter` the editor **doesn't** show the error message `Cannot find module 'jest-validate'` and it does format the code with the build-in options of VsCode.

I hope this issue gets resolved soon. 
If any other information is needed please do ask. Anyways thank you for your work.

**Comment by jetmirshatri** [comment]
I also found [this issue](https://github.com/Microsoft/vscode/issues/23615) on the VsCode repo. Notice the last comment of @dudeinthemirror. 
I am not using any other formatting extension(s) just this one.

**Comment by CiGit** [comment]
From what I read in the linked issue, it's MacOs related (I won't be able to help with that).
No file from that stack trace is ours.

Is prettier installed locally? ( in any node_modules up to `/` )
If you disable extensions all but prettier, does the problem persist?

**Comment by jetmirshatri** [comment]
@CiGit I only linked that issue because I searched for "Cannot find module 'jest-validate'" on the VsCode repo and found it mentioned there and saw that someone else had to disable this extension to make the error message disappear. 

No the prettier package itself is not installed in any of my projects (not as a dependency nor a devDependency). I just have this extension installed (`ext install prettier-vscode`).

I just tried it multiple times with all my extensions disabled but prettier and yes I keep getting the same error as shown here above and same console output.

**Comment by CiGit** [comment]
Can you go into the extension folder (I think somewhere like `~/.vscode/extensions/esbenp.prettier-vscode-0.12.0`) and `rm -Rf node_modules && npm i`

**Comment by jetmirshatri** [comment]
I my case it was `/Users/$USER/.vscode-insiders/extensions/esbenp.prettier-vscode-0.12.0` but yes that did it!! It is now working again as it should. Thank you very much!

**Comment by CiGit** [comment]
Nice.
Assumptions: corrupted install / permission issue. bad vsix package ?
