### ISSUE TITLE
Include option for arrowParens

### ISSUE THREAD

**Issue by ms007** [esbenp/prettier-vscode#61]
In the current prettier source there is an option to configure arrowParens. 

https://github.com/arijs/prettier-with-tabs/commit/0f918465dc1d16f8826268c658f55a27af7eb963

Could you please provide this configuration in the vscode settings too?

thanks a lot for your effort

**Comment by ms007** [comment]
Sorry 
Saw that this was added to a fork of prettier and not on prettier itself.
Closing this.

**Comment by jonricaurte** [comment]
This should be reopened. The arrowParens option was added in prettier 1.9.0:

https://github.com/prettier/prettier/releases/tag/1.9.0

**Comment by RobinMalfait** [comment]
It can stay closed since there is an open PR that bumps the version and allows this option.
