### ISSUE TITLE
[Fixed in Prettier@next] Unexpected whitespace added in JSX

### ISSUE THREAD

**Issue by corydeppen** [esbenp/prettier-vscode#63]
I just noticed unexpected formatting inside a simple block of JSX using version `0.12.0` in VS Code `1.10.2`. As you'll see below, whitespace is being added before and after the content of the `Button` component. The prettier-vscode output is inconsistent with the [online Prettier tool output](https://prettier.github.io/prettier/#%7B%22content%22%3A%22%3CButton%20type%3D%5C%22submit%5C%22%20color%3D%5C%22primary%5C%22%3E%5Cn%20%20Save%5Cn%3C%2FButton%3E%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Atrue%2C%22trailingComma%22%3A%22all%22%2C%22bracketSpacing%22%3Afalse%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22flow%22%2C%22doc%22%3Afalse%7D%7D). I also confirmed the output using the prettier-atom package (`0.26.0`) in Atom matches the online tool.

```jsx
{/* Before prettier-vscode */}
<Button type="submit" color="primary">
  Save
</Button>

{/* After prettier-vscode */}
<Button type="submit" color="primary">
  {' '}
  Save{' '}
</Button>
```

**Comment by CiGit** [comment]
Can you make sure you don't have a `whitespace` at the end of the first line ?
I can reproduce it [with it](https://prettier.github.io/prettier/#%7B%22content%22%3A%22%3CButton%20type%3D%5C%22submit%5C%22%20color%3D%5C%22primary%5C%22%3E%20%5Cn%20%20Save%5Cn%3C%2FButton%3E%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Atrue%2C%22trailingComma%22%3A%22all%22%2C%22bracketSpacing%22%3Afalse%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22flow%22%2C%22doc%22%3Afalse%7D%7D)

**Comment by corydeppen** [comment]
There isn't whitespace before or after prior to formatting. What I put into the Prettier online tool is directly from my source. I can copy what's in the online tool, put it in Code, then format it and it still adds the literals before and after. Below is taken from Atom (only because Code doesn't show line endings).

![prettier-vs-code-whitespace](https://cloud.githubusercontent.com/assets/313264/24830256/05049b6a-1c50-11e7-97d6-a5cb002ade36.png)

**Comment by CiGit** [comment]
I'm still unable to reproduce it with my setup.
Can you share 
- If you have any prettier installed in *any* `node_modules/prettier` upwards which may be used by this extension and thus it would be a different version used.
- your settings
- other extensions
- OS
- Line Endings

**Comment by corydeppen** [comment]
It seems to be related to the following setting:

`"prettier.parser": "flow"`

If I comment that out or change it to `babylon` the literals aren't added and the formatting appears as I'd expect.

**Comment by CiGit** [comment]
I've opened an issue prettier/prettier#1168 which is what I've found out.
Are you using `CRLF` line endings? (this is the unsure part about your issue)

**Comment by corydeppen** [comment]
Thanks for looking into this. Yes, the file is using `CRLF` line endings.

**Comment by vjeux** [comment]
Thanks for the report, I just sent https://github.com/prettier/prettier/pull/1170 to prettier in order to fix it! In the meantime, you can use babylon parser which supports everything that flow parser does and doesn't suffer from this bug.

**Comment by CiGit** [comment]
Thank you @vjeux.
Prettier has been patched. Waiting for next release to be bundled with prettier-vscode to close. `>0.22.0`
