### ISSUE TITLE
Instructions to change settings for Prettier

### ISSUE THREAD

**Issue by varungupta85** [esbenp/prettier-vscode#64]
In the README [Settings](https://github.com/esbenp/prettier-vscode#settings) section, it mentions different settings such as singleQuote, printWidth etc. that can be changed for Prettier. How/where do I set these settings?

**Comment by CiGit** [comment]
Like all other vscode settings
![image](https://cloud.githubusercontent.com/assets/1453420/24798136/c01b79da-1b94-11e7-8913-50891d93a2e7.png)
note: These settings are prefixed with `prettier.`

**Comment by varungupta85** [comment]
@CiGit Thanks for the response. The `prettier` prefix is what I was missing.

**Comment by grahamperich** [comment]
might be worth adding this to the readme for VS Code newbies. I found this via google

**Comment by oliwiah** [comment]
how did you manage to change there settings? I'm also trying to change the tabWidth but when I did what you said, I opened the read-only editor :(
