### ISSUE TITLE
Formatting is worse than using the CLI Tool

### ISSUE THREAD

**Issue by nwehrle** [esbenp/prettier-vscode#65]
### Description
I have a JSX File that I want to be prettier. I compare prettier CLI and your vscode plugin.

### Expected
It looks the same in CLI and vscode plugin

### Actual
It looks different

### Configuration:
```
  "editor.formatOnSave": true,
  "prettier.singleQuote": true,
  "prettier.parser": "flow",
  "prettier.printWidth": 120,
```

### Versions
prettier: 0.22.0
vscode: 1.11.1
plugin: 0.12.0

other plugins:
- eslint 1.2.8
- flow 0.5.0
- some themes

### CLI command
```
prettier --write --print-width 120 --single-quote --trailing-comma all --parser flow MinimalExample.jsx
```

### Input and CLI output
```
import React, { Component } from 'react';
import { func1, arr1 } from 'somewhere';

// elements
export default class Example extends Component {
  render() {
    describe('', () => {
      describe('', () => {
        describe('', () => {
          func1(arr1[0]).toEqual({
            first_name: 'Garfield',
            last_name: 'the Cat',
            profession: 'The cat food tester',
            employer_name: 'CK',
            zip_code: '5000',
            city: 'Aarau',
            phone: '+41 79 230 98 76'
          });
        });
      });
    });

    return <h1 className="demo">hi</h1>;
  }
}
```

### vscode output
```
import React, { Component } from 'react';
import { func1, arr1 } from 'somewhere';

// elements
export default class Example extends Component {
  render() {
    describe('', () => {
      describe('', () => {
        describe('', () => {
          func1(
            arr1[0],
          ).toEqual({ first_name: 'Garfield', last_name: 'the Cat', profession: 'The cat food tester', employer_name: 'CK', zip_code: '5000', city: 'Aarau', phone: '+41 79 230 98 76' });
        });
      });
    });

    return <h1 className='demo'>hi</h1>;
  }
}
```

### The annoyances
- it puts single quotes into the markup
- it puts the object into one line

**Comment by CiGit** [comment]
Thanks for your great bug report.

Version 0.12.0 is based on prettier 0.22.0 but it may be possible the extension picked up another version on your file's path (not the global one). Have you installed prettier in your project or parent project ? `node_modules/prettier`

I've run your file in my editor which also has those extensions and I get the output you would expect.

**Comment by nwehrle** [comment]
Yep, there is prettier in my local dependencies. It's 0.0.5.
Can I force the plugin to use another binary (in my case the global one)?

**Comment by CiGit** [comment]
There is no such option.
Algorithm is as follow:
1. search a local prettier
2. use bundled prettier if 1 failed.

You can replace bundled prettier by replacing it in the extension folder til next extension update. You may have compatibility troubles with the settings.

What I would suggest is depending on your needs is:
* Update your local dep
* Remove your local dep

**Comment by nwehrle** [comment]
Thank your for your time. Made a PR to my real dependency to update prettier.

**Comment by CiGit** [comment]
@nwehrle Prettier wasn't in **your** direct dependency ? if that's the case, this is not the expected behavior.

**Comment by nwehrle** [comment]
Nope. I depend on a project that depends on an old version of prettier. It is not a direct dependency and not in my package.json

**Comment by nwehrle** [comment]
Your PR works in my case. Thank you.
