### ISSUE TITLE
Nested ternary operations

### ISSUE THREAD

**Issue by yannickguillemot** [esbenp/prettier-vscode#66]
My VSCode User preferences:
```
{
    "prettier.printWidth": 120,
    "prettier.singleQuote": true
}
```

Original code:
``` js
const retVal = diff < -365 ? 'sameElse' :
  diff < -6 ? 'lastYear' :
  diff < -1 ? 'lastWeek' :
  diff < 0 ? 'lastDay' :
  diff < 1 ? 'sameDay' :
  diff < 2 ? 'nextDay' :
  diff < 7 ? 'nextWeek' :
  diff < 365 ? 'nextYear' : 'sameElse';
```

Expected:
``` js
const retVal = diff < -365 ?
      'sameElse' :
      diff < -6 ?
        'lastYear' :
        diff < -1 ?
          'lastWeek' :
          diff < 0 ?
            'lastDay' :
            diff < 1 ?
              'sameDay' :
              diff < 2 ?
                'nextDay' :
                diff < 7 ?
                'nextWeek' :
                  diff < 365 ?
                  'nextYear' :
                    'sameElse';
```

Result:
``` js
const retVal = diff < -365
      ? 'sameElse'
      : diff < -6
          ? 'lastYear'
          : diff < -1
              ? 'lastWeek'
              : diff < 0
                  ? 'lastDay'
                  : diff < 1
                      ? 'sameDay'
                      : diff < 2 ? 'nextDay' : diff < 7 ? 'nextWeek' : diff < 365 ? 'nextYear' : 'sameElse';
```

2 issues here:
1. The indents are set to 4 even though my user preferences specify a tab size of 2.
2. The formatting sort of gives up breaking lines for ternary (see last line). I am guessing this is because it decides that the rest of the operation can fit in one line knowing that the ruler is set to 120. I would still like to give the annotation consistency. Keeping this "ladder" all the way to the end would make it more readable.

I am pretty sure my second point should be more of an issue for the `prettier` project itself but I thought there was some conversations I can get from here first.

**Comment by CiGit** [comment]
It seems to me both of your issues are for prettier. Your output is [prettier's one](https://prettier.github.io/prettier/#%7B%22content%22%3A%22const%20retVal%20%3D%20diff%20%3C%20-365%20%3F%20'sameElse'%20%3A%5Cn%20%20diff%20%3C%20-6%20%3F%20'lastYear'%20%3A%5Cn%20%20diff%20%3C%20-1%20%3F%20'lastWeek'%20%3A%5Cn%20%20diff%20%3C%200%20%3F%20'lastDay'%20%3A%5Cn%20%20diff%20%3C%201%20%3F%20'sameDay'%20%3A%5Cn%20%20diff%20%3C%202%20%3F%20'nextDay'%20%3A%5Cn%20%20diff%20%3C%207%20%3F%20'nextWeek'%20%3A%5Cn%20%20diff%20%3C%20365%20%3F%20'nextYear'%20%3A%20'sameElse'%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A120%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Atrue%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22doc%22%3Afalse%7D%7D) as of prettier 0.22.0:

 ```js
const retVal = diff < -365
  ? 'sameElse'
  : diff < -6
      ? 'lastYear'
      : diff < -1
          ? 'lastWeek'
          : diff < 0
              ? 'lastDay'
              : diff < 1
                  ? 'sameDay'
                  : diff < 2 ? 'nextDay' : diff < 7 ? 'nextWeek' : diff < 365 ? 'nextYear' : 'sameElse';
```
1. see prettier/prettier#924
2. I've no knowledge of such an issue in prettier.

**Comment by CiGit** [comment]
Quite new there is prettier/prettier#1171 which seems to be your 2nd point.

**Comment by esbenp** [comment]
Closing this as this is a prettier issue :-) let me know if you think otherwise @CiGit @yannickguillemot
