### ISSUE TITLE
prettier parser, difference between `babylon` and `flow`

### ISSUE THREAD

**Issue by svipben** [esbenp/prettier-vscode#69]
Hello,

what is difference between `babylon` and `flow` in `parser` setting? Can you provide me some examples to understand it better?

Which one is better to use?

Thanks!

**Comment by esbenp** [comment]
Hey @svipben 

You should refer to the prettier repository for more information on how prettier works :-) https://github.com/prettier/prettier#language-support

**Comment by svipben** [comment]
@esbenp Hi, I asked question in `prettier` here - https://github.com/prettier/prettier/issues/1180.
