### ISSUE TITLE
Nothing happens

### ISSUE THREAD

**Issue by Arrow7000** [esbenp/prettier-vscode#7]
When I select `prettier` from the command menu absolutely nothing happens. Thoughts?

**Comment by Arrow7000** [comment]
Turns out everything needs to be selected when you execute the command. 

This could've been made clearer in my opinion.

**Comment by dvlsg** [comment]
I believe the intent is to make `prettier` format everything when nothing is selected. Tracking in #5

**Comment by esbenp** [comment]
Duplicate #5 

I will implement this later. Sorry it was unclear.

**Comment by esbenp** [comment]
Fixed in `0.3.1`
