### ISSUE TITLE
add `semi` option

### ISSUE THREAD

**Issue by yukulele** [esbenp/prettier-vscode#72]
prettier recently add option to remove `semi` option
https://github.com/prettier/prettier#api

**Comment by michrome** [comment]
+1, please support `semi`.

**Comment by esbenp** [comment]
I just opened #73 
Can you gents let me know when prettier tags a release with the `semi` option?

**Comment by michrome** [comment]
Will do! Thanks.

**Comment by yukulele** [comment]
https://github.com/prettier/prettier/releases/tag/1.0.0
