### ISSUE TITLE
Getting `Cannot read property 'prettier' of undefined` message

### ISSUE THREAD

**Issue by mogarick** [esbenp/prettier-vscode#75]
Hi, 
Everything was working fine but then suddenly I began to receive the error message `Cannot read property 'prettier' of undefined` when trying to format the code. The only difference I remember is that I updated my VSCode extensions.
I uninstalled the extension, reload and the reinstalled again the extension but he problem remains.

I have VSCode 1.11.1 installed on Mac OSX 10.11.6 (El Capitan).

**Comment by CiGit** [comment]
I've seen it, the fix is here #74 
As a current workaround, be sure your package.json contains `dependencies` and `devDependencies`. They may be empty `{}`

**Comment by mogarick** [comment]
Hi,
Mi `package.json` has `dependencies` and `devDependencies` objects with many properties.
![screen shot 2017-04-13 at 10 25 03 am](https://cloud.githubusercontent.com/assets/4414145/25011612/9753605a-2033-11e7-8885-36ca6cf9b4be.png)

**Comment by mogarick** [comment]
I've also checked the prettier `package.json` included with the extension and it's not empty either.

![screen shot 2017-04-13 at 10 32 28 am](https://cloud.githubusercontent.com/assets/4414145/25011924/8c2cf97e-2034-11e7-9834-8f8ad63a0d1c.png)

**Comment by CiGit** [comment]
Can you also check in parent package.json if any?

**Comment by jtulk** [comment]
I'm having the same problem after the update.

**Comment by CiGit** [comment]
Also no `package.json` without dependencies and devDependencies?
on the path from `/` to your file ?

**Comment by mogarick** [comment]
@CiGit the parent package.json also appears OK, with the dependencies properly declared (`esbenp.prettier-vscode-0.13.0/package.json`):
![screen shot 2017-04-13 at 1 26 59 pm](https://cloud.githubusercontent.com/assets/4414145/25018588/3e61a532-204d-11e7-85fa-a0ba1005c2e7.png)

**Comment by CiGit** [comment]
I was meaning in package.json located along the path
```
/
  package.json
  a/
    package.json
    b/
     .....
        workspace
          package.json
          dir/
            fileToFormat.js
```

This are the place where it could occur.

**Comment by mogarick** [comment]
@CiGit There only 1 `package.json` in my project tree is a CRA(create-react-app) and goes as follow:
```
/ProjectRoot
  /node_modules
  /src
    myfileToFormat.js
  package.json (My project. No empty deps objects)
```
the only additional `package.json` files are the ones related to the proper project dependencies but they're in the `node_modules` directory which is not along my src files path.

Is it more clear now?

**Comment by JesusIslam** [comment]
I got this exact same problem after updating.

**Comment by CiGit** [comment]
I still don't know where it can come from. Is it possible for you to debug it? I won't ask your entire file system :smiling_imp:

**Comment by jtulk** [comment]
Like @JesusIslam - things resolved for me when installing Prettier locally into the repo. So it seems like VSCode might not be checking for a globally installed copy and defaulting to that?

**Comment by JesusIslam** [comment]
@jtulk #65 seems right, it needs to be explicitly installed now.

**Comment by mogarick** [comment]
Indeed!
I installed prettier as devDependency and the problem was solved.
It would be excellent to add a note in the `readme.md` that prettier needs to be available as a dependency for the project or at least installed as a global (I didn't check if it works when prettier is installed as global module).

**Comment by JesusIslam** [comment]
@mogarick it didn't work as a global for me at least.

**Comment by CiGit** [comment]
Just published 0.13.1 with a patch that should correct this issue. At least what I could reproduce.

**Comment by jtulk** [comment]
@CiGit - Does the patch require a local install or will it work off a global install now? I'll be happy to do a PR to annotate the docs if it requires a local copy...

**Comment by CiGit** [comment]
It loads prettier packed with the extension if there is no local install. It doesn't use your globally installed prettier.
PR welcome to update https://github.com/esbenp/prettier-vscode#prettier-resolution ;-)

**Comment by tizmagik** [comment]
I just hit this today VSCode Version 1.16.1, prettier-vscode 0.24.0 and had to install prettier locally to fix it (`npm i -D prettier`) it was working fine without that previously...

**Comment by CiGit** [comment]
@tizmagik How was your setup before you installed prettier? Stack trace?

**Comment by tizmagik** [comment]
Where would the stacktrace be? All I saw was the Cannot read property 'prettier' of undefined message in the output tab

**Comment by CiGit** [comment]
Damn, I also forgot some informations here. I meant debug it :-)
clone it, npm i, open it in vscode and <kbd>F5</kbd> (Start debugging)
