### ISSUE TITLE
Do I need to have `prettier` installed in my project to use this plugin?

### ISSUE THREAD

**Issue by svipben** [esbenp/prettier-vscode#79]
Hello,

Do I need to have `prettier` installed in my project to use this plugin? Because right now I have `prettier` installed in my project, but do I need it or plugin is not using it?

Thanks.

**Comment by CiGit** [comment]
It will take the one from your project if it is installed but it is able to use the one provided with this extension

**Comment by svipben** [comment]
@CiGit so which one method is better? To have it installed in project or no? Since I'm not using `prettier` CLI, only this plugin with VS Code to format my code.

**Comment by CiGit** [comment]
Well, the embed is prettier 0.22 *currently* so if you want to use 1.1+ you should install it for now.
The trouble with different version are options. We currently do not provide `semi` or `useTabs` so you won't be able to use them.
It simply works if you use the embed one.

**Comment by svipben** [comment]
@CiGit Thanks for info. I will be using `prettier` in my project then. But I like this idea to choose if you want you can use embed one or you install package and it will use it. Nice work :+1:
