### ISSUE TITLE
Define path to prettier

### ISSUE THREAD

**Issue by DanielMSchmidt** [esbenp/prettier-vscode#84]
Hi there,

I am currently using your implementation in a mono repo environment, so the package.json is deply nested and the prettier version may even differ in different parts I open. I would like to be able to configure something like:

```json
{
   "prettierPaths": [
      "**/project-part-a": "/project/project-part-a/node_modules/.bin/prettier",
      "**/project-part-b": "/project/project-part-b/node_modules/.bin/prettier"
   ]
}
```

If I understand it correct this is not possible currently, right?

**Comment by CiGit** [comment]
As long as prettier is a dependency or a devDependency of your `project-part-{a,b}` it will make use of the relevant prettier for a file laying under `project-part-{a,b}`

If I understand correctly what you would like, there is no need for it.
## Example
format `/project/project-part-b/sub/folder/file.js` will load `/project/project-part-b/node_modules/prettier/index.js` as long as `/project/project-part-b/package.json` contains 
prettier.

**Comment by CiGit** [comment]
I forgot to mention: in that case, you won't be able to have different settings. And I think it will fail if you use prettier < 0.19.0 due to how we pass settings in.

**Comment by DanielMSchmidt** [comment]
Oh okay, thank you for the clairification, I just assume this because it formatted my code incorrectly. The reason was an old version of prettier installed :) 

Thank you so much for your help!
