### ISSUE TITLE
Vue support ?

### ISSUE THREAD

**Issue by jbrodriguez** [esbenp/prettier-vscode#87]
What I gather from this issue https://github.com/prettier/prettier/issues/651, is that vue support should be implemented in something like the editor.

prettier-atom had this PR https://github.com/prettier/prettier-atom/pull/44

Wondering if something similar can be done for vscode ?

**Comment by CiGit** [comment]
It should be possible to do something. (maybe ugly, It seems vscode doesn't have embedded language support)
I don't use vue myself. Has vscode a language associated with it?

PR welcome ! :fire:

**Comment by jbrodriguez** [comment]
> I don't use vue myself. Has vscode a language associated with it?

It has something called single file component (SFC). In a single file, you have html, script and styles sections.

So the idea is to single out the script (javascript/typescript) section and send it to prettier for formatting.

I'll try to take a look at the code and see how this can be done.

**Comment by wuhaosky** [comment]
@jbrodriguez  I'll be waiting for your good news.

**Comment by jsappme** [comment]
+1

**Comment by muhajirframe** [comment]
+1

**Comment by colwilson** [comment]
+1

**Comment by CiGit** [comment]
Will support it once it lands in prettier. And it seems it will.

**Comment by denisw** [comment]
Prettier has support for Vue components now (for the `<script>` and `<style>` parts): https://github.com/prettier/prettier/issues/2097

**Comment by CiGit** [comment]
So does this extension. It's just disabled by default. `disabledLanguages`
