### ISSUE TITLE
Comments are not being formatted correctly (empty line between each comment line)

### ISSUE THREAD

**Issue by frankhale** [esbenp/prettier-vscode#88]
I'm seeing odd behavior on some of my files when I use Prettier to format them. The issue is specifically with comment lines. Prettier is inserting an empty line between each line and I cannot figure out why or how to prevent it from doing this. Please see screenshots below:

Before formatting:

![before-prettier-formatting](https://cloud.githubusercontent.com/assets/190154/25252084/a6cca15c-25e9-11e7-8dea-41a53ec17ab4.PNG)

After formatting:

![after-prettier-formatting](https://cloud.githubusercontent.com/assets/190154/25252086/a90d0bd2-25e9-11e7-9ddc-3b671621e38d.PNG)

**Comment by frankhale** [comment]
Just to add a bit more context it doesn't do this for every block of comments I have like this.  It seems to be random and I've not been able to figure out why for some sections it inserts an empty line between each comment line.

**Comment by CiGit** [comment]
We will need a little more context.
- Have you installed prettier in your project?
- Your settings?
- Your line endings?
- A minimal reproduction case?

If you run prettier 1.1.0 (the version we currently ship) on your file does the same happen ? I will update prettier today.

If you run prettier installed in your project does it happen ? Update it :-)

**Comment by frankhale** [comment]
Looks like I have version 0.14 of Prettier. Installed via the VS Code extension marketplace.

> Have you installed prettier in your project?

Prettier is installed as an extension to VS Code. I did not know it was even possible to install it in my project.

> Your settings?

My settings for VS Code are pretty simple

```json
{
  "editor.fontFamily": "'Fira Code', Consolas, 'Courier New', monospace",
  "editor.fontSize": 18,
  "editor.rulers": [
    80
  ],
  "editor.detectIndentation": false,
  "editor.tabSize": 2,
  "editor.fontLigatures": true,
  "editor.formatOnSave": true,
  "workbench.activityBar.visible": true,
  "window.zoomLevel": 0,
  "typescript.check.tscVersion": false,
  "sync.gist": "4f7f176b92d58caf6bd87db2a5749aa3",
  "sync.lastUpload": "1970-01-01T00:00:00.000Z",
  "sync.autoDownload": false,
  "sync.autoUpload": false,
  "sync.lastDownload": "1970-01-01T00:00:00.000Z",
  "sync.version": 262,
  "sync.showSummary": true,
  "sync.forceDownload": false,
  "sync.anonymousGist": false,
  "vsicons.projectDetection.autoReload": true,
  "workbench.colorTheme": "1337",
  "editor.wordWrap": "off",
  "editor.minimap.enabled": true,
  "sync.host": "",
  "sync.pathPrefix": "",
  "workbench.iconTheme": "material-icon-theme"
}
```

> Your line endings?

I have not explicitly set this. I'm running VS Code on Windows 10.

> A minimal reproduction case?

```javascript
export default class FooBar {
  bar() {
    this.Foo(FOODATA);
    
    // This is a test
    // this is another test
    // why is Prettier adding newlines between each comment after formatting?
    // I have no idea but it's driving me nuts
  }
}
```

Here are before and after screenshots of that minimal test case:

Before:

![before](https://cloud.githubusercontent.com/assets/190154/25276252/4795b858-2667-11e7-82f4-1d26ee423667.PNG)

After:

![after](https://cloud.githubusercontent.com/assets/190154/25276258/4e364290-2667-11e7-937a-193eb6b107be.PNG)

> If you run prettier installed in your project does it happen ? Update it :-)

Don't know how to install prettier in my project since it's just a VS Code extension that I am using. I cannot update it because version online is only 0.14.0. I will gladly try 1.1.0 when it's released.

**Comment by frankhale** [comment]
It appears as though a function call proceeded by multiline comments is the problem. If I remove the function call prior to the comments the comments will not have new lines inserted between each line after formatting.

**Comment by CiGit** [comment]
Found it. 
What I meant by prettier 1.1.0 is the formatter not this extension which uses it

CRLF line endings + prettier@1.1.0

It's fixed in prettier@1.2.2

**Comment by CiGit** [comment]
new version with prettier@1.2.2 published.
let me know ;-)

**Comment by frankhale** [comment]
I just updated, problem solved. THANK YOU!
