### ISSUE TITLE
Not all files are processed with my config options

### ISSUE THREAD

**Issue by wmertens** [esbenp/prettier-vscode#89]
When I `Format Document`, some of my files get the no-semi and other settings I have enabled, and others don't.

Some files that get the proper formatting:
* lib/react.jsx
* src/_server/database/Clients.js
* src/lib/priceCalc.js
* src/lib/jsurl.js
* src/styles/index.js

Some files that get the default formatting:
* lib/index.js
* lib/client/init.js
* src/_server/database/index.js
* src/_server/database/helpers.js
* src/lib/helpers.js
* src/frontend/components/Pages/PageContent.jsx

As you can see, it's a mixed bag, but it is consistent across restarts. Thoughts? Ways to debug?

**Comment by CiGit** [comment]
Weird. Settings are taken from vscode only. Global, workspace and language (this part is done by vscode)
I see you have same file types in same folder with different behavior and thus I've no hypothesis.
To debug, you can clone this repo, open it in vscode and run the debug config.
A good start would be [breakpoint](https://github.com/esbenp/prettier-vscode/blob/de35db60ac253724fa00467be59af485cc84061d/src/PrettierEditProvider.ts#L39)

**Comment by CiGit** [comment]
Stalled, please reopen if this is still the case.
