### ISSUE TITLE
Class properties don't preserve empty lines

### ISSUE THREAD

**Issue by jozan** [esbenp/prettier-vscode#93]
It should preserve empty lines but the extension doesn't do it.

![prettier-vscode-tussi](https://cloud.githubusercontent.com/assets/388265/25420718/1c8fdc98-2a62-11e7-8227-f272c06d3cca.gif)

**Comment by CiGit** [comment]
It seems to be produced by the flow parser.
Without semi after `state={};` but it looks like you don't use them.
This is an issue with prettier not with the extension

**Comment by jozan** [comment]
Thanks for your reply and extension! I reported this to prettier repo: https://github.com/prettier/prettier/issues/1423
