### ISSUE TITLE
Format files with ts extension

### ISSUE THREAD

**Issue by newtack** [esbenp/prettier-vscode#94]
How can I make sure that files with ts extension are formatted with prettier too?

Running prettier on a ts file from the command line works, but the "Format Document" command in VSCode for ts file does not work, it uses the default formatter rather than prettier.

**Comment by CiGit** [comment]
Typescript is not yet supported by prettier

**Comment by newtack** [comment]
Typescript is not fully supported, but most of it is working already and when I manually invoke prettier it does the job in most cases. Rather than manually invoking prettier, I'd like it to be invoked automatically when saving typescript files. 

Is this supported now, and if not, can it be supported soon?

**Comment by CiGit** [comment]
The problem like you mentioned is
> not fully supported

*Supported* constructs are those similar to flow. 
Prettier started integrating the typescript parser. Currently undocumented prettier/prettier#1318.
I don't want to provide a *work in progress* into this extension which will fail too often for now. But I will want to provide something in testing stage (maybe behind a flag). This will help to find out some prettier-typescript issues.

There are currently a lot of typescript issues / pr opened.
I'm unable to tell you when this will be.

If you really want to. You can fork this extension and make little changes to be able to run it on typescript. And even open a PR with it which could be used *soon*. I think #57 should be done before we can do this anyway :-)

**Comment by CiGit** [comment]
Fixed in Version 0.18.0
