### ISSUE TITLE
perttier according to file suffix

### ISSUE THREAD

**Issue by monkindey** [esbenp/prettier-vscode#98]
I set the vscode setting `editor.formatOnSave` to `true` and save the tpl file, but the prettier try to format my tpl. So, can we support one config item that can let the prettier to format it or ignore it. such as:

```js
prettier.file.exclude: /.tpl$/
```

Any idea welcome.

**Comment by CiGit** [comment]
What is a tpl file? if it's javascript or javascriptreact or jsx then prettier runs on them. If it's not one of those then it's an other formater you have.
To exclude files, please refer to #32

**Comment by monkindey** [comment]
Thanks for your relay, The tpl file is which be wrote by nunjucks. I will try to figure out which formater make it. Thank you.

**Comment by monkindey** [comment]
When I disable the prettier extension and it still be formatted. So it's not the problem of prettier extension.

**Comment by CiGit** [comment]
Thanks for confirming.
